name: jobber

services:
  jobber-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pg-pass
      - POSTGRES_DB=database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network-jobber-internal

  jobber-server:
    image: eithan1231/jobber:latest
    container_name: "jobber-server"
    depends_on:
      - "jobber-db"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jobber-data:/app/config
    environment:
      DATABASE_URL: postgresql://pg-user:pg-pass@jobber-db/database
      DOCKER_HOST: unix:///var/run/docker.sock

      # The Docker network that the jobber runners will attach to, this should
      # be isolated form the jobber-db. The following is configured to access
      # "network-jobber-runner" network, however docker-compose auto-prefixes
      # the compose project name to all networks to avoid conflicts.
      RUNNER_CONTAINER_DOCKER_NETWORK: jobber_network-jobber-runner

      # Each instance of jobber-server should have a unique name. If you have
      # multiple instances of jobber-server running, each instance should have
      # a unique JOBBER_NAME. This is used for multiple reasons, such as
      # - If jobber-server unexpectedly crashes, this is crucial for
      #   identifying which dangling containers are managed by jobber-server
      # - Attached to metrics to identify which jobber-server instance
      #   is responsible for which jobs
      JOBBER_NAME: Jobba
    ports:
      - 3000:3000
      - 3001:3001
    restart: "unless-stopped"
    networks:
      - network-jobber-internal
      - network-jobber-runner

volumes:
  postgres-data:
  jobber-data:

networks:
  network-jobber-internal:
    driver: bridge
  network-jobber-runner:
    driver: bridge
