// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: gateway.proto

/* eslint-disable */

export const protobufPackage = "GatewayAPI";

/**  */
export type GatewayAPIDefinition = typeof GatewayAPIDefinition;
export const GatewayAPIDefinition = { name: "GatewayAPI", fullName: "GatewayAPI.GatewayAPI", methods: {} } as const;

export interface GatewayAPIServiceImplementation<CallContextExt = {}> {
}

export interface GatewayAPIClient<CallOptionsExt = {}> {
}
