// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: general.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Item as Item2 } from "./basics/action.js";
import { Item as Item1 } from "./basics/job-version.js";
import { Item } from "./basics/job.js";
import {
  Item as Item4,
  Item_Status,
  item_StatusFromJSON,
  item_StatusToJSON,
  item_StatusToNumber,
} from "./basics/runner.js";
import { Item as Item3 } from "./basics/trigger.js";

export const protobufPackage = "GeneralAPI";

/** getJob * */
export interface JobRequest {
  jobId: string;
}

export interface JobResponse {
  job: Item | undefined;
}

/** getJobs * */
export interface JobsRequest {
}

export interface JobsResponse {
  jobs: Item[];
}

/** getJobVersion * */
export interface JobVersionRequest {
  jobVersionId: string;
}

export interface JobVersionResponse {
  jobVersion: Item1 | undefined;
}

/** getJobVersionLatest * */
export interface JobVersionLatestRequest {
  jobId: string;
}

export interface JobVersionLatestResponse {
  jobVersion: Item1 | undefined;
}

/** getJobVersions * */
export interface JobVersionsRequest {
  jobId: string;
}

export interface JobVersionsResponse {
  jobVersions: Item1[];
}

/** getJobVersionArchive * */
export interface JobVersionArchiveRequest {
  jobId: string;
  jobVersionId: string;
}

export interface JobVersionArchiveResponse {
  seq: number;
  data: Uint8Array;
  end: boolean;
}

/** getJobAction * */
export interface JobActionRequest {
  jobId: string;
  actionId: string;
}

export interface JobActionResponse {
  action: Item2 | undefined;
}

/** getJobActionLatest * */
export interface JobActionLatestRequest {
  jobId: string;
}

export interface JobActionLatestResponse {
  action: Item2 | undefined;
}

/** getJobActions * */
export interface JobActionsRequest {
  jobId: string;
  versionId?: string | undefined;
}

export interface JobActionsResponse {
  actions: Item2[];
}

/** getJobTrigger * */
export interface JobTriggerRequest {
  jobId: string;
  triggerId: string;
}

export interface JobTriggerResponse {
  trigger: Item3 | undefined;
}

/** getJobTriggers * */
export interface JobTriggersRequest {
  jobId: string;
  versionId?: string | undefined;
}

export interface JobTriggersResponse {
  triggers: Item3[];
}

/** getJobTriggersLatest * */
export interface JobTriggersLatestRequest {
  jobId: string;
}

export interface JobTriggersLatestResponse {
  triggers: Item3[];
}

/** getRunner * */
export interface RunnerRequest {
  runnerId: string;
}

export interface RunnerResponse {
  runner: Item4 | undefined;
}

/** getRunners * */
export interface RunnersRequest {
  jobId?: string | undefined;
  versionId?: string | undefined;
  actionId?: string | undefined;
  status?: Item_Status | undefined;
}

export interface RunnersResponse {
  runners: Item4[];
}

/** getStoreItem * */
export interface StoreItemRequest {
  jobId: string;
  key: string;
}

export interface StoreItemResponse {
  key: string;
  value: string;
}

/** setStoreItem * */
export interface SetStoreItemRequest {
  jobId: string;
  key: string;
  value: string;
  ttl?: number | undefined;
}

export interface SetStoreItemResponse {
  key: string;
  value: string;
}

/** deleteStoreItem * */
export interface DeleteStoreItemRequest {
  jobId: string;
  key: string;
}

export interface DeleteStoreItemResponse {
  key: string;
}

/** publishMqttMessage * */
export interface PublishMqttMessageRequest {
  jobId: string;
  topic: string;
  payload: string;
}

export interface PublishMqttMessageResponse {
}

/** createRunner * */
export interface CreateSoftRunnerRequest {
  jobId: string;
  versionId: string;
  actionId: string;
}

export interface CreateSoftRunnerResponse {
  runner: Item4 | undefined;
}

/** getTemplates * */
export interface TemplatesRequest {
}

export interface TemplatesResponse {
  templateBadGateway: string;
}

function createBaseJobRequest(): JobRequest {
  return { jobId: "" };
}

export const JobRequest: MessageFns<JobRequest> = {
  encode(message: JobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobRequest>): JobRequest {
    return JobRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobRequest>): JobRequest {
    const message = createBaseJobRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobResponse(): JobResponse {
  return { job: undefined };
}

export const JobResponse: MessageFns<JobResponse> = {
  encode(message: JobResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.job !== undefined) {
      Item.encode(message.job, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.job = Item.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobResponse {
    return { job: isSet(object.job) ? Item.fromJSON(object.job) : undefined };
  },

  toJSON(message: JobResponse): unknown {
    const obj: any = {};
    if (message.job !== undefined) {
      obj.job = Item.toJSON(message.job);
    }
    return obj;
  },

  create(base?: DeepPartial<JobResponse>): JobResponse {
    return JobResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobResponse>): JobResponse {
    const message = createBaseJobResponse();
    message.job = (object.job !== undefined && object.job !== null) ? Item.fromPartial(object.job) : undefined;
    return message;
  },
};

function createBaseJobsRequest(): JobsRequest {
  return {};
}

export const JobsRequest: MessageFns<JobsRequest> = {
  encode(_: JobsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): JobsRequest {
    return {};
  },

  toJSON(_: JobsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<JobsRequest>): JobsRequest {
    return JobsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<JobsRequest>): JobsRequest {
    const message = createBaseJobsRequest();
    return message;
  },
};

function createBaseJobsResponse(): JobsResponse {
  return { jobs: [] };
}

export const JobsResponse: MessageFns<JobsResponse> = {
  encode(message: JobsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.jobs) {
      Item.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobs.push(Item.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobsResponse {
    return { jobs: globalThis.Array.isArray(object?.jobs) ? object.jobs.map((e: any) => Item.fromJSON(e)) : [] };
  },

  toJSON(message: JobsResponse): unknown {
    const obj: any = {};
    if (message.jobs?.length) {
      obj.jobs = message.jobs.map((e) => Item.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobsResponse>): JobsResponse {
    return JobsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobsResponse>): JobsResponse {
    const message = createBaseJobsResponse();
    message.jobs = object.jobs?.map((e) => Item.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobVersionRequest(): JobVersionRequest {
  return { jobVersionId: "" };
}

export const JobVersionRequest: MessageFns<JobVersionRequest> = {
  encode(message: JobVersionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobVersionId !== "") {
      writer.uint32(10).string(message.jobVersionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionRequest {
    return { jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "" };
  },

  toJSON(message: JobVersionRequest): unknown {
    const obj: any = {};
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionRequest>): JobVersionRequest {
    return JobVersionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionRequest>): JobVersionRequest {
    const message = createBaseJobVersionRequest();
    message.jobVersionId = object.jobVersionId ?? "";
    return message;
  },
};

function createBaseJobVersionResponse(): JobVersionResponse {
  return { jobVersion: undefined };
}

export const JobVersionResponse: MessageFns<JobVersionResponse> = {
  encode(message: JobVersionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobVersion !== undefined) {
      Item1.encode(message.jobVersion, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersion = Item1.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionResponse {
    return { jobVersion: isSet(object.jobVersion) ? Item1.fromJSON(object.jobVersion) : undefined };
  },

  toJSON(message: JobVersionResponse): unknown {
    const obj: any = {};
    if (message.jobVersion !== undefined) {
      obj.jobVersion = Item1.toJSON(message.jobVersion);
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionResponse>): JobVersionResponse {
    return JobVersionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionResponse>): JobVersionResponse {
    const message = createBaseJobVersionResponse();
    message.jobVersion = (object.jobVersion !== undefined && object.jobVersion !== null)
      ? Item1.fromPartial(object.jobVersion)
      : undefined;
    return message;
  },
};

function createBaseJobVersionLatestRequest(): JobVersionLatestRequest {
  return { jobId: "" };
}

export const JobVersionLatestRequest: MessageFns<JobVersionLatestRequest> = {
  encode(message: JobVersionLatestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionLatestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionLatestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionLatestRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobVersionLatestRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionLatestRequest>): JobVersionLatestRequest {
    return JobVersionLatestRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionLatestRequest>): JobVersionLatestRequest {
    const message = createBaseJobVersionLatestRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobVersionLatestResponse(): JobVersionLatestResponse {
  return { jobVersion: undefined };
}

export const JobVersionLatestResponse: MessageFns<JobVersionLatestResponse> = {
  encode(message: JobVersionLatestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobVersion !== undefined) {
      Item1.encode(message.jobVersion, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionLatestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionLatestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersion = Item1.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionLatestResponse {
    return { jobVersion: isSet(object.jobVersion) ? Item1.fromJSON(object.jobVersion) : undefined };
  },

  toJSON(message: JobVersionLatestResponse): unknown {
    const obj: any = {};
    if (message.jobVersion !== undefined) {
      obj.jobVersion = Item1.toJSON(message.jobVersion);
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionLatestResponse>): JobVersionLatestResponse {
    return JobVersionLatestResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionLatestResponse>): JobVersionLatestResponse {
    const message = createBaseJobVersionLatestResponse();
    message.jobVersion = (object.jobVersion !== undefined && object.jobVersion !== null)
      ? Item1.fromPartial(object.jobVersion)
      : undefined;
    return message;
  },
};

function createBaseJobVersionsRequest(): JobVersionsRequest {
  return { jobId: "" };
}

export const JobVersionsRequest: MessageFns<JobVersionsRequest> = {
  encode(message: JobVersionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionsRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobVersionsRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionsRequest>): JobVersionsRequest {
    return JobVersionsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionsRequest>): JobVersionsRequest {
    const message = createBaseJobVersionsRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobVersionsResponse(): JobVersionsResponse {
  return { jobVersions: [] };
}

export const JobVersionsResponse: MessageFns<JobVersionsResponse> = {
  encode(message: JobVersionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.jobVersions) {
      Item1.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersions.push(Item1.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionsResponse {
    return {
      jobVersions: globalThis.Array.isArray(object?.jobVersions)
        ? object.jobVersions.map((e: any) => Item1.fromJSON(e))
        : [],
    };
  },

  toJSON(message: JobVersionsResponse): unknown {
    const obj: any = {};
    if (message.jobVersions?.length) {
      obj.jobVersions = message.jobVersions.map((e) => Item1.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionsResponse>): JobVersionsResponse {
    return JobVersionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionsResponse>): JobVersionsResponse {
    const message = createBaseJobVersionsResponse();
    message.jobVersions = object.jobVersions?.map((e) => Item1.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobVersionArchiveRequest(): JobVersionArchiveRequest {
  return { jobId: "", jobVersionId: "" };
}

export const JobVersionArchiveRequest: MessageFns<JobVersionArchiveRequest> = {
  encode(message: JobVersionArchiveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.jobVersionId !== "") {
      writer.uint32(18).string(message.jobVersionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionArchiveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionArchiveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionArchiveRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "",
    };
  },

  toJSON(message: JobVersionArchiveRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionArchiveRequest>): JobVersionArchiveRequest {
    return JobVersionArchiveRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionArchiveRequest>): JobVersionArchiveRequest {
    const message = createBaseJobVersionArchiveRequest();
    message.jobId = object.jobId ?? "";
    message.jobVersionId = object.jobVersionId ?? "";
    return message;
  },
};

function createBaseJobVersionArchiveResponse(): JobVersionArchiveResponse {
  return { seq: 0, data: new Uint8Array(0), end: false };
}

export const JobVersionArchiveResponse: MessageFns<JobVersionArchiveResponse> = {
  encode(message: JobVersionArchiveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).uint64(message.seq);
    }
    if (message.data.length !== 0) {
      writer.uint32(18).bytes(message.data);
    }
    if (message.end !== false) {
      writer.uint32(24).bool(message.end);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionArchiveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionArchiveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.end = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionArchiveResponse {
    return {
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      end: isSet(object.end) ? globalThis.Boolean(object.end) : false,
    };
  },

  toJSON(message: JobVersionArchiveResponse): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.end !== false) {
      obj.end = message.end;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionArchiveResponse>): JobVersionArchiveResponse {
    return JobVersionArchiveResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionArchiveResponse>): JobVersionArchiveResponse {
    const message = createBaseJobVersionArchiveResponse();
    message.seq = object.seq ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    message.end = object.end ?? false;
    return message;
  },
};

function createBaseJobActionRequest(): JobActionRequest {
  return { jobId: "", actionId: "" };
}

export const JobActionRequest: MessageFns<JobActionRequest> = {
  encode(message: JobActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.actionId !== "") {
      writer.uint32(18).string(message.actionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
    };
  },

  toJSON(message: JobActionRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionRequest>): JobActionRequest {
    return JobActionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionRequest>): JobActionRequest {
    const message = createBaseJobActionRequest();
    message.jobId = object.jobId ?? "";
    message.actionId = object.actionId ?? "";
    return message;
  },
};

function createBaseJobActionResponse(): JobActionResponse {
  return { action: undefined };
}

export const JobActionResponse: MessageFns<JobActionResponse> = {
  encode(message: JobActionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== undefined) {
      Item2.encode(message.action, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.action = Item2.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionResponse {
    return { action: isSet(object.action) ? Item2.fromJSON(object.action) : undefined };
  },

  toJSON(message: JobActionResponse): unknown {
    const obj: any = {};
    if (message.action !== undefined) {
      obj.action = Item2.toJSON(message.action);
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionResponse>): JobActionResponse {
    return JobActionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionResponse>): JobActionResponse {
    const message = createBaseJobActionResponse();
    message.action = (object.action !== undefined && object.action !== null)
      ? Item2.fromPartial(object.action)
      : undefined;
    return message;
  },
};

function createBaseJobActionLatestRequest(): JobActionLatestRequest {
  return { jobId: "" };
}

export const JobActionLatestRequest: MessageFns<JobActionLatestRequest> = {
  encode(message: JobActionLatestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionLatestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionLatestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionLatestRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobActionLatestRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionLatestRequest>): JobActionLatestRequest {
    return JobActionLatestRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionLatestRequest>): JobActionLatestRequest {
    const message = createBaseJobActionLatestRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobActionLatestResponse(): JobActionLatestResponse {
  return { action: undefined };
}

export const JobActionLatestResponse: MessageFns<JobActionLatestResponse> = {
  encode(message: JobActionLatestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== undefined) {
      Item2.encode(message.action, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionLatestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionLatestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.action = Item2.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionLatestResponse {
    return { action: isSet(object.action) ? Item2.fromJSON(object.action) : undefined };
  },

  toJSON(message: JobActionLatestResponse): unknown {
    const obj: any = {};
    if (message.action !== undefined) {
      obj.action = Item2.toJSON(message.action);
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionLatestResponse>): JobActionLatestResponse {
    return JobActionLatestResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionLatestResponse>): JobActionLatestResponse {
    const message = createBaseJobActionLatestResponse();
    message.action = (object.action !== undefined && object.action !== null)
      ? Item2.fromPartial(object.action)
      : undefined;
    return message;
  },
};

function createBaseJobActionsRequest(): JobActionsRequest {
  return { jobId: "", versionId: undefined };
}

export const JobActionsRequest: MessageFns<JobActionsRequest> = {
  encode(message: JobActionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionsRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
    };
  },

  toJSON(message: JobActionsRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionsRequest>): JobActionsRequest {
    return JobActionsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionsRequest>): JobActionsRequest {
    const message = createBaseJobActionsRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? undefined;
    return message;
  },
};

function createBaseJobActionsResponse(): JobActionsResponse {
  return { actions: [] };
}

export const JobActionsResponse: MessageFns<JobActionsResponse> = {
  encode(message: JobActionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.actions) {
      Item2.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actions.push(Item2.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionsResponse {
    return {
      actions: globalThis.Array.isArray(object?.actions) ? object.actions.map((e: any) => Item2.fromJSON(e)) : [],
    };
  },

  toJSON(message: JobActionsResponse): unknown {
    const obj: any = {};
    if (message.actions?.length) {
      obj.actions = message.actions.map((e) => Item2.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionsResponse>): JobActionsResponse {
    return JobActionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionsResponse>): JobActionsResponse {
    const message = createBaseJobActionsResponse();
    message.actions = object.actions?.map((e) => Item2.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobTriggerRequest(): JobTriggerRequest {
  return { jobId: "", triggerId: "" };
}

export const JobTriggerRequest: MessageFns<JobTriggerRequest> = {
  encode(message: JobTriggerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.triggerId !== "") {
      writer.uint32(18).string(message.triggerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.triggerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggerRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      triggerId: isSet(object.triggerId) ? globalThis.String(object.triggerId) : "",
    };
  },

  toJSON(message: JobTriggerRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.triggerId !== "") {
      obj.triggerId = message.triggerId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggerRequest>): JobTriggerRequest {
    return JobTriggerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggerRequest>): JobTriggerRequest {
    const message = createBaseJobTriggerRequest();
    message.jobId = object.jobId ?? "";
    message.triggerId = object.triggerId ?? "";
    return message;
  },
};

function createBaseJobTriggerResponse(): JobTriggerResponse {
  return { trigger: undefined };
}

export const JobTriggerResponse: MessageFns<JobTriggerResponse> = {
  encode(message: JobTriggerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trigger !== undefined) {
      Item3.encode(message.trigger, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trigger = Item3.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggerResponse {
    return { trigger: isSet(object.trigger) ? Item3.fromJSON(object.trigger) : undefined };
  },

  toJSON(message: JobTriggerResponse): unknown {
    const obj: any = {};
    if (message.trigger !== undefined) {
      obj.trigger = Item3.toJSON(message.trigger);
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggerResponse>): JobTriggerResponse {
    return JobTriggerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggerResponse>): JobTriggerResponse {
    const message = createBaseJobTriggerResponse();
    message.trigger = (object.trigger !== undefined && object.trigger !== null)
      ? Item3.fromPartial(object.trigger)
      : undefined;
    return message;
  },
};

function createBaseJobTriggersRequest(): JobTriggersRequest {
  return { jobId: "", versionId: undefined };
}

export const JobTriggersRequest: MessageFns<JobTriggersRequest> = {
  encode(message: JobTriggersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggersRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
    };
  },

  toJSON(message: JobTriggersRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggersRequest>): JobTriggersRequest {
    return JobTriggersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggersRequest>): JobTriggersRequest {
    const message = createBaseJobTriggersRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? undefined;
    return message;
  },
};

function createBaseJobTriggersResponse(): JobTriggersResponse {
  return { triggers: [] };
}

export const JobTriggersResponse: MessageFns<JobTriggersResponse> = {
  encode(message: JobTriggersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.triggers) {
      Item3.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.triggers.push(Item3.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggersResponse {
    return {
      triggers: globalThis.Array.isArray(object?.triggers) ? object.triggers.map((e: any) => Item3.fromJSON(e)) : [],
    };
  },

  toJSON(message: JobTriggersResponse): unknown {
    const obj: any = {};
    if (message.triggers?.length) {
      obj.triggers = message.triggers.map((e) => Item3.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggersResponse>): JobTriggersResponse {
    return JobTriggersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggersResponse>): JobTriggersResponse {
    const message = createBaseJobTriggersResponse();
    message.triggers = object.triggers?.map((e) => Item3.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobTriggersLatestRequest(): JobTriggersLatestRequest {
  return { jobId: "" };
}

export const JobTriggersLatestRequest: MessageFns<JobTriggersLatestRequest> = {
  encode(message: JobTriggersLatestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggersLatestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggersLatestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggersLatestRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobTriggersLatestRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggersLatestRequest>): JobTriggersLatestRequest {
    return JobTriggersLatestRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggersLatestRequest>): JobTriggersLatestRequest {
    const message = createBaseJobTriggersLatestRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobTriggersLatestResponse(): JobTriggersLatestResponse {
  return { triggers: [] };
}

export const JobTriggersLatestResponse: MessageFns<JobTriggersLatestResponse> = {
  encode(message: JobTriggersLatestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.triggers) {
      Item3.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggersLatestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggersLatestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.triggers.push(Item3.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggersLatestResponse {
    return {
      triggers: globalThis.Array.isArray(object?.triggers) ? object.triggers.map((e: any) => Item3.fromJSON(e)) : [],
    };
  },

  toJSON(message: JobTriggersLatestResponse): unknown {
    const obj: any = {};
    if (message.triggers?.length) {
      obj.triggers = message.triggers.map((e) => Item3.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggersLatestResponse>): JobTriggersLatestResponse {
    return JobTriggersLatestResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggersLatestResponse>): JobTriggersLatestResponse {
    const message = createBaseJobTriggersLatestResponse();
    message.triggers = object.triggers?.map((e) => Item3.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRunnerRequest(): RunnerRequest {
  return { runnerId: "" };
}

export const RunnerRequest: MessageFns<RunnerRequest> = {
  encode(message: RunnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runnerId !== "") {
      writer.uint32(10).string(message.runnerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runnerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnerRequest {
    return { runnerId: isSet(object.runnerId) ? globalThis.String(object.runnerId) : "" };
  },

  toJSON(message: RunnerRequest): unknown {
    const obj: any = {};
    if (message.runnerId !== "") {
      obj.runnerId = message.runnerId;
    }
    return obj;
  },

  create(base?: DeepPartial<RunnerRequest>): RunnerRequest {
    return RunnerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerRequest>): RunnerRequest {
    const message = createBaseRunnerRequest();
    message.runnerId = object.runnerId ?? "";
    return message;
  },
};

function createBaseRunnerResponse(): RunnerResponse {
  return { runner: undefined };
}

export const RunnerResponse: MessageFns<RunnerResponse> = {
  encode(message: RunnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runner !== undefined) {
      Item4.encode(message.runner, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runner = Item4.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnerResponse {
    return { runner: isSet(object.runner) ? Item4.fromJSON(object.runner) : undefined };
  },

  toJSON(message: RunnerResponse): unknown {
    const obj: any = {};
    if (message.runner !== undefined) {
      obj.runner = Item4.toJSON(message.runner);
    }
    return obj;
  },

  create(base?: DeepPartial<RunnerResponse>): RunnerResponse {
    return RunnerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerResponse>): RunnerResponse {
    const message = createBaseRunnerResponse();
    message.runner = (object.runner !== undefined && object.runner !== null)
      ? Item4.fromPartial(object.runner)
      : undefined;
    return message;
  },
};

function createBaseRunnersRequest(): RunnersRequest {
  return { jobId: undefined, versionId: undefined, actionId: undefined, status: undefined };
}

export const RunnersRequest: MessageFns<RunnersRequest> = {
  encode(message: RunnersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== undefined) {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    if (message.actionId !== undefined) {
      writer.uint32(26).string(message.actionId);
    }
    if (message.status !== undefined) {
      writer.uint32(32).int32(item_StatusToNumber(message.status));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = item_StatusFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnersRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : undefined,
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : undefined,
      status: isSet(object.status) ? item_StatusFromJSON(object.status) : undefined,
    };
  },

  toJSON(message: RunnersRequest): unknown {
    const obj: any = {};
    if (message.jobId !== undefined) {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.actionId !== undefined) {
      obj.actionId = message.actionId;
    }
    if (message.status !== undefined) {
      obj.status = item_StatusToJSON(message.status);
    }
    return obj;
  },

  create(base?: DeepPartial<RunnersRequest>): RunnersRequest {
    return RunnersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnersRequest>): RunnersRequest {
    const message = createBaseRunnersRequest();
    message.jobId = object.jobId ?? undefined;
    message.versionId = object.versionId ?? undefined;
    message.actionId = object.actionId ?? undefined;
    message.status = object.status ?? undefined;
    return message;
  },
};

function createBaseRunnersResponse(): RunnersResponse {
  return { runners: [] };
}

export const RunnersResponse: MessageFns<RunnersResponse> = {
  encode(message: RunnersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.runners) {
      Item4.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runners.push(Item4.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnersResponse {
    return {
      runners: globalThis.Array.isArray(object?.runners) ? object.runners.map((e: any) => Item4.fromJSON(e)) : [],
    };
  },

  toJSON(message: RunnersResponse): unknown {
    const obj: any = {};
    if (message.runners?.length) {
      obj.runners = message.runners.map((e) => Item4.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RunnersResponse>): RunnersResponse {
    return RunnersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnersResponse>): RunnersResponse {
    const message = createBaseRunnersResponse();
    message.runners = object.runners?.map((e) => Item4.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStoreItemRequest(): StoreItemRequest {
  return { jobId: "", key: "" };
}

export const StoreItemRequest: MessageFns<StoreItemRequest> = {
  encode(message: StoreItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreItemRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
    };
  },

  toJSON(message: StoreItemRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create(base?: DeepPartial<StoreItemRequest>): StoreItemRequest {
    return StoreItemRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StoreItemRequest>): StoreItemRequest {
    const message = createBaseStoreItemRequest();
    message.jobId = object.jobId ?? "";
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseStoreItemResponse(): StoreItemResponse {
  return { key: "", value: "" };
}

export const StoreItemResponse: MessageFns<StoreItemResponse> = {
  encode(message: StoreItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreItemResponse {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: StoreItemResponse): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<StoreItemResponse>): StoreItemResponse {
    return StoreItemResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StoreItemResponse>): StoreItemResponse {
    const message = createBaseStoreItemResponse();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSetStoreItemRequest(): SetStoreItemRequest {
  return { jobId: "", key: "", value: "", ttl: undefined };
}

export const SetStoreItemRequest: MessageFns<SetStoreItemRequest> = {
  encode(message: SetStoreItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(26).string(message.value);
    }
    if (message.ttl !== undefined) {
      writer.uint32(32).uint32(message.ttl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetStoreItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetStoreItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.ttl = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetStoreItemRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : undefined,
    };
  },

  toJSON(message: SetStoreItemRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.ttl !== undefined) {
      obj.ttl = Math.round(message.ttl);
    }
    return obj;
  },

  create(base?: DeepPartial<SetStoreItemRequest>): SetStoreItemRequest {
    return SetStoreItemRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetStoreItemRequest>): SetStoreItemRequest {
    const message = createBaseSetStoreItemRequest();
    message.jobId = object.jobId ?? "";
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    message.ttl = object.ttl ?? undefined;
    return message;
  },
};

function createBaseSetStoreItemResponse(): SetStoreItemResponse {
  return { key: "", value: "" };
}

export const SetStoreItemResponse: MessageFns<SetStoreItemResponse> = {
  encode(message: SetStoreItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetStoreItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetStoreItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetStoreItemResponse {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SetStoreItemResponse): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<SetStoreItemResponse>): SetStoreItemResponse {
    return SetStoreItemResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetStoreItemResponse>): SetStoreItemResponse {
    const message = createBaseSetStoreItemResponse();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDeleteStoreItemRequest(): DeleteStoreItemRequest {
  return { jobId: "", key: "" };
}

export const DeleteStoreItemRequest: MessageFns<DeleteStoreItemRequest> = {
  encode(message: DeleteStoreItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteStoreItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteStoreItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteStoreItemRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
    };
  },

  toJSON(message: DeleteStoreItemRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteStoreItemRequest>): DeleteStoreItemRequest {
    return DeleteStoreItemRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteStoreItemRequest>): DeleteStoreItemRequest {
    const message = createBaseDeleteStoreItemRequest();
    message.jobId = object.jobId ?? "";
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseDeleteStoreItemResponse(): DeleteStoreItemResponse {
  return { key: "" };
}

export const DeleteStoreItemResponse: MessageFns<DeleteStoreItemResponse> = {
  encode(message: DeleteStoreItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteStoreItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteStoreItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteStoreItemResponse {
    return { key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: DeleteStoreItemResponse): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteStoreItemResponse>): DeleteStoreItemResponse {
    return DeleteStoreItemResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteStoreItemResponse>): DeleteStoreItemResponse {
    const message = createBaseDeleteStoreItemResponse();
    message.key = object.key ?? "";
    return message;
  },
};

function createBasePublishMqttMessageRequest(): PublishMqttMessageRequest {
  return { jobId: "", topic: "", payload: "" };
}

export const PublishMqttMessageRequest: MessageFns<PublishMqttMessageRequest> = {
  encode(message: PublishMqttMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    if (message.payload !== "") {
      writer.uint32(26).string(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishMqttMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishMqttMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublishMqttMessageRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
    };
  },

  toJSON(message: PublishMqttMessageRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    return obj;
  },

  create(base?: DeepPartial<PublishMqttMessageRequest>): PublishMqttMessageRequest {
    return PublishMqttMessageRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PublishMqttMessageRequest>): PublishMqttMessageRequest {
    const message = createBasePublishMqttMessageRequest();
    message.jobId = object.jobId ?? "";
    message.topic = object.topic ?? "";
    message.payload = object.payload ?? "";
    return message;
  },
};

function createBasePublishMqttMessageResponse(): PublishMqttMessageResponse {
  return {};
}

export const PublishMqttMessageResponse: MessageFns<PublishMqttMessageResponse> = {
  encode(_: PublishMqttMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishMqttMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishMqttMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PublishMqttMessageResponse {
    return {};
  },

  toJSON(_: PublishMqttMessageResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<PublishMqttMessageResponse>): PublishMqttMessageResponse {
    return PublishMqttMessageResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<PublishMqttMessageResponse>): PublishMqttMessageResponse {
    const message = createBasePublishMqttMessageResponse();
    return message;
  },
};

function createBaseCreateSoftRunnerRequest(): CreateSoftRunnerRequest {
  return { jobId: "", versionId: "", actionId: "" };
}

export const CreateSoftRunnerRequest: MessageFns<CreateSoftRunnerRequest> = {
  encode(message: CreateSoftRunnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== "") {
      writer.uint32(18).string(message.versionId);
    }
    if (message.actionId !== "") {
      writer.uint32(26).string(message.actionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSoftRunnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSoftRunnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSoftRunnerRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : "",
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
    };
  },

  toJSON(message: CreateSoftRunnerRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== "") {
      obj.versionId = message.versionId;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSoftRunnerRequest>): CreateSoftRunnerRequest {
    return CreateSoftRunnerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSoftRunnerRequest>): CreateSoftRunnerRequest {
    const message = createBaseCreateSoftRunnerRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? "";
    message.actionId = object.actionId ?? "";
    return message;
  },
};

function createBaseCreateSoftRunnerResponse(): CreateSoftRunnerResponse {
  return { runner: undefined };
}

export const CreateSoftRunnerResponse: MessageFns<CreateSoftRunnerResponse> = {
  encode(message: CreateSoftRunnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runner !== undefined) {
      Item4.encode(message.runner, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSoftRunnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSoftRunnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runner = Item4.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSoftRunnerResponse {
    return { runner: isSet(object.runner) ? Item4.fromJSON(object.runner) : undefined };
  },

  toJSON(message: CreateSoftRunnerResponse): unknown {
    const obj: any = {};
    if (message.runner !== undefined) {
      obj.runner = Item4.toJSON(message.runner);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSoftRunnerResponse>): CreateSoftRunnerResponse {
    return CreateSoftRunnerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSoftRunnerResponse>): CreateSoftRunnerResponse {
    const message = createBaseCreateSoftRunnerResponse();
    message.runner = (object.runner !== undefined && object.runner !== null)
      ? Item4.fromPartial(object.runner)
      : undefined;
    return message;
  },
};

function createBaseTemplatesRequest(): TemplatesRequest {
  return {};
}

export const TemplatesRequest: MessageFns<TemplatesRequest> = {
  encode(_: TemplatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TemplatesRequest {
    return {};
  },

  toJSON(_: TemplatesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<TemplatesRequest>): TemplatesRequest {
    return TemplatesRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<TemplatesRequest>): TemplatesRequest {
    const message = createBaseTemplatesRequest();
    return message;
  },
};

function createBaseTemplatesResponse(): TemplatesResponse {
  return { templateBadGateway: "" };
}

export const TemplatesResponse: MessageFns<TemplatesResponse> = {
  encode(message: TemplatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateBadGateway !== "") {
      writer.uint32(10).string(message.templateBadGateway);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templateBadGateway = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplatesResponse {
    return { templateBadGateway: isSet(object.templateBadGateway) ? globalThis.String(object.templateBadGateway) : "" };
  },

  toJSON(message: TemplatesResponse): unknown {
    const obj: any = {};
    if (message.templateBadGateway !== "") {
      obj.templateBadGateway = message.templateBadGateway;
    }
    return obj;
  },

  create(base?: DeepPartial<TemplatesResponse>): TemplatesResponse {
    return TemplatesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TemplatesResponse>): TemplatesResponse {
    const message = createBaseTemplatesResponse();
    message.templateBadGateway = object.templateBadGateway ?? "";
    return message;
  },
};

export type GeneralAPIDefinition = typeof GeneralAPIDefinition;
export const GeneralAPIDefinition = {
  name: "GeneralAPI",
  fullName: "GeneralAPI.GeneralAPI",
  methods: {
    getJob: {
      name: "getJob",
      requestType: JobRequest,
      requestStream: false,
      responseType: JobResponse,
      responseStream: false,
      options: {},
    },
    getJobs: {
      name: "getJobs",
      requestType: JobsRequest,
      requestStream: false,
      responseType: JobsResponse,
      responseStream: false,
      options: {},
    },
    getJobVersion: {
      name: "getJobVersion",
      requestType: JobVersionRequest,
      requestStream: false,
      responseType: JobVersionResponse,
      responseStream: false,
      options: {},
    },
    getJobVersionLatest: {
      name: "getJobVersionLatest",
      requestType: JobVersionLatestRequest,
      requestStream: false,
      responseType: JobVersionLatestResponse,
      responseStream: false,
      options: {},
    },
    getJobVersions: {
      name: "getJobVersions",
      requestType: JobVersionsRequest,
      requestStream: false,
      responseType: JobVersionsResponse,
      responseStream: false,
      options: {},
    },
    getJobVersionArchive: {
      name: "getJobVersionArchive",
      requestType: JobVersionArchiveRequest,
      requestStream: false,
      responseType: JobVersionArchiveResponse,
      responseStream: true,
      options: {},
    },
    getJobAction: {
      name: "getJobAction",
      requestType: JobActionRequest,
      requestStream: false,
      responseType: JobActionResponse,
      responseStream: false,
      options: {},
    },
    getJobActionLatest: {
      name: "getJobActionLatest",
      requestType: JobActionLatestRequest,
      requestStream: false,
      responseType: JobActionLatestResponse,
      responseStream: false,
      options: {},
    },
    getJobActions: {
      name: "getJobActions",
      requestType: JobActionsRequest,
      requestStream: false,
      responseType: JobActionsResponse,
      responseStream: false,
      options: {},
    },
    getJobTrigger: {
      name: "getJobTrigger",
      requestType: JobTriggerRequest,
      requestStream: false,
      responseType: JobTriggerResponse,
      responseStream: false,
      options: {},
    },
    getJobTriggers: {
      name: "getJobTriggers",
      requestType: JobTriggersRequest,
      requestStream: false,
      responseType: JobTriggersResponse,
      responseStream: false,
      options: {},
    },
    getJobTriggersLatest: {
      name: "getJobTriggersLatest",
      requestType: JobTriggersLatestRequest,
      requestStream: false,
      responseType: JobTriggersLatestResponse,
      responseStream: false,
      options: {},
    },
    getRunner: {
      name: "getRunner",
      requestType: RunnerRequest,
      requestStream: false,
      responseType: RunnerResponse,
      responseStream: false,
      options: {},
    },
    getRunners: {
      name: "getRunners",
      requestType: RunnersRequest,
      requestStream: false,
      responseType: RunnersResponse,
      responseStream: false,
      options: {},
    },
    getStoreItem: {
      name: "getStoreItem",
      requestType: StoreItemRequest,
      requestStream: false,
      responseType: StoreItemResponse,
      responseStream: false,
      options: {},
    },
    setStoreItem: {
      name: "setStoreItem",
      requestType: SetStoreItemRequest,
      requestStream: false,
      responseType: SetStoreItemResponse,
      responseStream: false,
      options: {},
    },
    deleteStoreItem: {
      name: "deleteStoreItem",
      requestType: DeleteStoreItemRequest,
      requestStream: false,
      responseType: DeleteStoreItemResponse,
      responseStream: false,
      options: {},
    },
    /** This will likely be migrated to its own service similar to the GatewayAPI */
    publishMqttMessage: {
      name: "publishMqttMessage",
      requestType: PublishMqttMessageRequest,
      requestStream: false,
      responseType: PublishMqttMessageResponse,
      responseStream: false,
      options: {},
    },
    createSoftRunner: {
      name: "createSoftRunner",
      requestType: CreateSoftRunnerRequest,
      requestStream: false,
      responseType: CreateSoftRunnerResponse,
      responseStream: false,
      options: {},
    },
    getTemplates: {
      name: "getTemplates",
      requestType: TemplatesRequest,
      requestStream: false,
      responseType: TemplatesResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface GeneralAPIServiceImplementation<CallContextExt = {}> {
  getJob(request: JobRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JobResponse>>;
  getJobs(request: JobsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JobsResponse>>;
  getJobVersion(
    request: JobVersionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobVersionResponse>>;
  getJobVersionLatest(
    request: JobVersionLatestRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobVersionLatestResponse>>;
  getJobVersions(
    request: JobVersionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobVersionsResponse>>;
  getJobVersionArchive(
    request: JobVersionArchiveRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<JobVersionArchiveResponse>>;
  getJobAction(
    request: JobActionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobActionResponse>>;
  getJobActionLatest(
    request: JobActionLatestRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobActionLatestResponse>>;
  getJobActions(
    request: JobActionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobActionsResponse>>;
  getJobTrigger(
    request: JobTriggerRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobTriggerResponse>>;
  getJobTriggers(
    request: JobTriggersRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobTriggersResponse>>;
  getJobTriggersLatest(
    request: JobTriggersLatestRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobTriggersLatestResponse>>;
  getRunner(request: RunnerRequest, context: CallContext & CallContextExt): Promise<DeepPartial<RunnerResponse>>;
  getRunners(request: RunnersRequest, context: CallContext & CallContextExt): Promise<DeepPartial<RunnersResponse>>;
  getStoreItem(
    request: StoreItemRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<StoreItemResponse>>;
  setStoreItem(
    request: SetStoreItemRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetStoreItemResponse>>;
  deleteStoreItem(
    request: DeleteStoreItemRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<DeleteStoreItemResponse>>;
  /** This will likely be migrated to its own service similar to the GatewayAPI */
  publishMqttMessage(
    request: PublishMqttMessageRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<PublishMqttMessageResponse>>;
  createSoftRunner(
    request: CreateSoftRunnerRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CreateSoftRunnerResponse>>;
  getTemplates(
    request: TemplatesRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<TemplatesResponse>>;
}

export interface GeneralAPIClient<CallOptionsExt = {}> {
  getJob(request: DeepPartial<JobRequest>, options?: CallOptions & CallOptionsExt): Promise<JobResponse>;
  getJobs(request: DeepPartial<JobsRequest>, options?: CallOptions & CallOptionsExt): Promise<JobsResponse>;
  getJobVersion(
    request: DeepPartial<JobVersionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobVersionResponse>;
  getJobVersionLatest(
    request: DeepPartial<JobVersionLatestRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobVersionLatestResponse>;
  getJobVersions(
    request: DeepPartial<JobVersionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobVersionsResponse>;
  getJobVersionArchive(
    request: DeepPartial<JobVersionArchiveRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<JobVersionArchiveResponse>;
  getJobAction(
    request: DeepPartial<JobActionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobActionResponse>;
  getJobActionLatest(
    request: DeepPartial<JobActionLatestRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobActionLatestResponse>;
  getJobActions(
    request: DeepPartial<JobActionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobActionsResponse>;
  getJobTrigger(
    request: DeepPartial<JobTriggerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobTriggerResponse>;
  getJobTriggers(
    request: DeepPartial<JobTriggersRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobTriggersResponse>;
  getJobTriggersLatest(
    request: DeepPartial<JobTriggersLatestRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobTriggersLatestResponse>;
  getRunner(request: DeepPartial<RunnerRequest>, options?: CallOptions & CallOptionsExt): Promise<RunnerResponse>;
  getRunners(request: DeepPartial<RunnersRequest>, options?: CallOptions & CallOptionsExt): Promise<RunnersResponse>;
  getStoreItem(
    request: DeepPartial<StoreItemRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<StoreItemResponse>;
  setStoreItem(
    request: DeepPartial<SetStoreItemRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetStoreItemResponse>;
  deleteStoreItem(
    request: DeepPartial<DeleteStoreItemRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<DeleteStoreItemResponse>;
  /** This will likely be migrated to its own service similar to the GatewayAPI */
  publishMqttMessage(
    request: DeepPartial<PublishMqttMessageRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<PublishMqttMessageResponse>;
  createSoftRunner(
    request: DeepPartial<CreateSoftRunnerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CreateSoftRunnerResponse>;
  getTemplates(
    request: DeepPartial<TemplatesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<TemplatesResponse>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
