// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: general.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Item as Item2 } from "./basics/action.js";
import { Item as Item1 } from "./basics/job-version.js";
import { Item } from "./basics/job.js";
import {
  Item as Item4,
  Item_Status,
  item_StatusFromJSON,
  item_StatusToJSON,
  item_StatusToNumber,
} from "./basics/runner.js";
import { Item as Item3 } from "./basics/trigger.js";

export const protobufPackage = "GeneralAPI";

/** getJob * */
export interface JobRequest {
  jobId: string;
}

export interface JobResponse {
  job: Item | undefined;
}

/** getJobs * */
export interface JobsRequest {
}

export interface JobsResponse {
  jobs: Item[];
}

/** getJobVersion * */
export interface JobVersionRequest {
  jobVersionId: string;
}

export interface JobVersionResponse {
  jobVersion: Item1 | undefined;
}

/** getJobVersions * */
export interface JobVersionsRequest {
  jobId: string;
}

export interface JobVersionsResponse {
  jobVersions: Item1[];
}

/** getJobAction * */
export interface JobActionRequest {
  jobId: string;
  actionId: string;
}

export interface JobActionResponse {
  action: Item2 | undefined;
}

/** getJobActions * */
export interface JobActionsRequest {
  jobId: string;
  versionId?: string | undefined;
}

export interface JobActionsResponse {
  actions: Item2[];
}

/** getJobTrigger * */
export interface JobTriggerRequest {
  jobId: string;
  triggerId: string;
}

export interface JobTriggerResponse {
  trigger: Item3 | undefined;
}

/** getJobTriggers * */
export interface JobTriggersRequest {
  jobId: string;
  versionId?: string | undefined;
}

export interface JobTriggersResponse {
  triggers: Item3[];
}

/** getRunner * */
export interface RunnerRequest {
  runnerId: string;
}

export interface RunnerResponse {
  runner: Item4 | undefined;
}

/** getRunners * */
export interface RunnersRequest {
  jobId?: string | undefined;
  versionId?: string | undefined;
  actionId?: string | undefined;
  status?: Item_Status | undefined;
}

export interface RunnersResponse {
  runners: Item4[];
}

function createBaseJobRequest(): JobRequest {
  return { jobId: "" };
}

export const JobRequest: MessageFns<JobRequest> = {
  encode(message: JobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobRequest>): JobRequest {
    return JobRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobRequest>): JobRequest {
    const message = createBaseJobRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobResponse(): JobResponse {
  return { job: undefined };
}

export const JobResponse: MessageFns<JobResponse> = {
  encode(message: JobResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.job !== undefined) {
      Item.encode(message.job, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.job = Item.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobResponse {
    return { job: isSet(object.job) ? Item.fromJSON(object.job) : undefined };
  },

  toJSON(message: JobResponse): unknown {
    const obj: any = {};
    if (message.job !== undefined) {
      obj.job = Item.toJSON(message.job);
    }
    return obj;
  },

  create(base?: DeepPartial<JobResponse>): JobResponse {
    return JobResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobResponse>): JobResponse {
    const message = createBaseJobResponse();
    message.job = (object.job !== undefined && object.job !== null) ? Item.fromPartial(object.job) : undefined;
    return message;
  },
};

function createBaseJobsRequest(): JobsRequest {
  return {};
}

export const JobsRequest: MessageFns<JobsRequest> = {
  encode(_: JobsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): JobsRequest {
    return {};
  },

  toJSON(_: JobsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<JobsRequest>): JobsRequest {
    return JobsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<JobsRequest>): JobsRequest {
    const message = createBaseJobsRequest();
    return message;
  },
};

function createBaseJobsResponse(): JobsResponse {
  return { jobs: [] };
}

export const JobsResponse: MessageFns<JobsResponse> = {
  encode(message: JobsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.jobs) {
      Item.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobs.push(Item.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobsResponse {
    return { jobs: globalThis.Array.isArray(object?.jobs) ? object.jobs.map((e: any) => Item.fromJSON(e)) : [] };
  },

  toJSON(message: JobsResponse): unknown {
    const obj: any = {};
    if (message.jobs?.length) {
      obj.jobs = message.jobs.map((e) => Item.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobsResponse>): JobsResponse {
    return JobsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobsResponse>): JobsResponse {
    const message = createBaseJobsResponse();
    message.jobs = object.jobs?.map((e) => Item.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobVersionRequest(): JobVersionRequest {
  return { jobVersionId: "" };
}

export const JobVersionRequest: MessageFns<JobVersionRequest> = {
  encode(message: JobVersionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobVersionId !== "") {
      writer.uint32(10).string(message.jobVersionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionRequest {
    return { jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "" };
  },

  toJSON(message: JobVersionRequest): unknown {
    const obj: any = {};
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionRequest>): JobVersionRequest {
    return JobVersionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionRequest>): JobVersionRequest {
    const message = createBaseJobVersionRequest();
    message.jobVersionId = object.jobVersionId ?? "";
    return message;
  },
};

function createBaseJobVersionResponse(): JobVersionResponse {
  return { jobVersion: undefined };
}

export const JobVersionResponse: MessageFns<JobVersionResponse> = {
  encode(message: JobVersionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobVersion !== undefined) {
      Item1.encode(message.jobVersion, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersion = Item1.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionResponse {
    return { jobVersion: isSet(object.jobVersion) ? Item1.fromJSON(object.jobVersion) : undefined };
  },

  toJSON(message: JobVersionResponse): unknown {
    const obj: any = {};
    if (message.jobVersion !== undefined) {
      obj.jobVersion = Item1.toJSON(message.jobVersion);
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionResponse>): JobVersionResponse {
    return JobVersionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionResponse>): JobVersionResponse {
    const message = createBaseJobVersionResponse();
    message.jobVersion = (object.jobVersion !== undefined && object.jobVersion !== null)
      ? Item1.fromPartial(object.jobVersion)
      : undefined;
    return message;
  },
};

function createBaseJobVersionsRequest(): JobVersionsRequest {
  return { jobId: "" };
}

export const JobVersionsRequest: MessageFns<JobVersionsRequest> = {
  encode(message: JobVersionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionsRequest {
    return { jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "" };
  },

  toJSON(message: JobVersionsRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionsRequest>): JobVersionsRequest {
    return JobVersionsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionsRequest>): JobVersionsRequest {
    const message = createBaseJobVersionsRequest();
    message.jobId = object.jobId ?? "";
    return message;
  },
};

function createBaseJobVersionsResponse(): JobVersionsResponse {
  return { jobVersions: [] };
}

export const JobVersionsResponse: MessageFns<JobVersionsResponse> = {
  encode(message: JobVersionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.jobVersions) {
      Item1.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobVersionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobVersionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobVersions.push(Item1.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobVersionsResponse {
    return {
      jobVersions: globalThis.Array.isArray(object?.jobVersions)
        ? object.jobVersions.map((e: any) => Item1.fromJSON(e))
        : [],
    };
  },

  toJSON(message: JobVersionsResponse): unknown {
    const obj: any = {};
    if (message.jobVersions?.length) {
      obj.jobVersions = message.jobVersions.map((e) => Item1.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobVersionsResponse>): JobVersionsResponse {
    return JobVersionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobVersionsResponse>): JobVersionsResponse {
    const message = createBaseJobVersionsResponse();
    message.jobVersions = object.jobVersions?.map((e) => Item1.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobActionRequest(): JobActionRequest {
  return { jobId: "", actionId: "" };
}

export const JobActionRequest: MessageFns<JobActionRequest> = {
  encode(message: JobActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.actionId !== "") {
      writer.uint32(18).string(message.actionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
    };
  },

  toJSON(message: JobActionRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionRequest>): JobActionRequest {
    return JobActionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionRequest>): JobActionRequest {
    const message = createBaseJobActionRequest();
    message.jobId = object.jobId ?? "";
    message.actionId = object.actionId ?? "";
    return message;
  },
};

function createBaseJobActionResponse(): JobActionResponse {
  return { action: undefined };
}

export const JobActionResponse: MessageFns<JobActionResponse> = {
  encode(message: JobActionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== undefined) {
      Item2.encode(message.action, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.action = Item2.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionResponse {
    return { action: isSet(object.action) ? Item2.fromJSON(object.action) : undefined };
  },

  toJSON(message: JobActionResponse): unknown {
    const obj: any = {};
    if (message.action !== undefined) {
      obj.action = Item2.toJSON(message.action);
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionResponse>): JobActionResponse {
    return JobActionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionResponse>): JobActionResponse {
    const message = createBaseJobActionResponse();
    message.action = (object.action !== undefined && object.action !== null)
      ? Item2.fromPartial(object.action)
      : undefined;
    return message;
  },
};

function createBaseJobActionsRequest(): JobActionsRequest {
  return { jobId: "", versionId: undefined };
}

export const JobActionsRequest: MessageFns<JobActionsRequest> = {
  encode(message: JobActionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionsRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
    };
  },

  toJSON(message: JobActionsRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionsRequest>): JobActionsRequest {
    return JobActionsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionsRequest>): JobActionsRequest {
    const message = createBaseJobActionsRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? undefined;
    return message;
  },
};

function createBaseJobActionsResponse(): JobActionsResponse {
  return { actions: [] };
}

export const JobActionsResponse: MessageFns<JobActionsResponse> = {
  encode(message: JobActionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.actions) {
      Item2.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobActionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobActionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actions.push(Item2.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobActionsResponse {
    return {
      actions: globalThis.Array.isArray(object?.actions) ? object.actions.map((e: any) => Item2.fromJSON(e)) : [],
    };
  },

  toJSON(message: JobActionsResponse): unknown {
    const obj: any = {};
    if (message.actions?.length) {
      obj.actions = message.actions.map((e) => Item2.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobActionsResponse>): JobActionsResponse {
    return JobActionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobActionsResponse>): JobActionsResponse {
    const message = createBaseJobActionsResponse();
    message.actions = object.actions?.map((e) => Item2.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobTriggerRequest(): JobTriggerRequest {
  return { jobId: "", triggerId: "" };
}

export const JobTriggerRequest: MessageFns<JobTriggerRequest> = {
  encode(message: JobTriggerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.triggerId !== "") {
      writer.uint32(18).string(message.triggerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.triggerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggerRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      triggerId: isSet(object.triggerId) ? globalThis.String(object.triggerId) : "",
    };
  },

  toJSON(message: JobTriggerRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.triggerId !== "") {
      obj.triggerId = message.triggerId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggerRequest>): JobTriggerRequest {
    return JobTriggerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggerRequest>): JobTriggerRequest {
    const message = createBaseJobTriggerRequest();
    message.jobId = object.jobId ?? "";
    message.triggerId = object.triggerId ?? "";
    return message;
  },
};

function createBaseJobTriggerResponse(): JobTriggerResponse {
  return { trigger: undefined };
}

export const JobTriggerResponse: MessageFns<JobTriggerResponse> = {
  encode(message: JobTriggerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trigger !== undefined) {
      Item3.encode(message.trigger, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trigger = Item3.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggerResponse {
    return { trigger: isSet(object.trigger) ? Item3.fromJSON(object.trigger) : undefined };
  },

  toJSON(message: JobTriggerResponse): unknown {
    const obj: any = {};
    if (message.trigger !== undefined) {
      obj.trigger = Item3.toJSON(message.trigger);
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggerResponse>): JobTriggerResponse {
    return JobTriggerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggerResponse>): JobTriggerResponse {
    const message = createBaseJobTriggerResponse();
    message.trigger = (object.trigger !== undefined && object.trigger !== null)
      ? Item3.fromPartial(object.trigger)
      : undefined;
    return message;
  },
};

function createBaseJobTriggersRequest(): JobTriggersRequest {
  return { jobId: "", versionId: undefined };
}

export const JobTriggersRequest: MessageFns<JobTriggersRequest> = {
  encode(message: JobTriggersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggersRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
    };
  },

  toJSON(message: JobTriggersRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggersRequest>): JobTriggersRequest {
    return JobTriggersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggersRequest>): JobTriggersRequest {
    const message = createBaseJobTriggersRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? undefined;
    return message;
  },
};

function createBaseJobTriggersResponse(): JobTriggersResponse {
  return { triggers: [] };
}

export const JobTriggersResponse: MessageFns<JobTriggersResponse> = {
  encode(message: JobTriggersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.triggers) {
      Item3.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobTriggersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobTriggersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.triggers.push(Item3.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobTriggersResponse {
    return {
      triggers: globalThis.Array.isArray(object?.triggers) ? object.triggers.map((e: any) => Item3.fromJSON(e)) : [],
    };
  },

  toJSON(message: JobTriggersResponse): unknown {
    const obj: any = {};
    if (message.triggers?.length) {
      obj.triggers = message.triggers.map((e) => Item3.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<JobTriggersResponse>): JobTriggersResponse {
    return JobTriggersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobTriggersResponse>): JobTriggersResponse {
    const message = createBaseJobTriggersResponse();
    message.triggers = object.triggers?.map((e) => Item3.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRunnerRequest(): RunnerRequest {
  return { runnerId: "" };
}

export const RunnerRequest: MessageFns<RunnerRequest> = {
  encode(message: RunnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runnerId !== "") {
      writer.uint32(10).string(message.runnerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runnerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnerRequest {
    return { runnerId: isSet(object.runnerId) ? globalThis.String(object.runnerId) : "" };
  },

  toJSON(message: RunnerRequest): unknown {
    const obj: any = {};
    if (message.runnerId !== "") {
      obj.runnerId = message.runnerId;
    }
    return obj;
  },

  create(base?: DeepPartial<RunnerRequest>): RunnerRequest {
    return RunnerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerRequest>): RunnerRequest {
    const message = createBaseRunnerRequest();
    message.runnerId = object.runnerId ?? "";
    return message;
  },
};

function createBaseRunnerResponse(): RunnerResponse {
  return { runner: undefined };
}

export const RunnerResponse: MessageFns<RunnerResponse> = {
  encode(message: RunnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runner !== undefined) {
      Item4.encode(message.runner, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runner = Item4.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnerResponse {
    return { runner: isSet(object.runner) ? Item4.fromJSON(object.runner) : undefined };
  },

  toJSON(message: RunnerResponse): unknown {
    const obj: any = {};
    if (message.runner !== undefined) {
      obj.runner = Item4.toJSON(message.runner);
    }
    return obj;
  },

  create(base?: DeepPartial<RunnerResponse>): RunnerResponse {
    return RunnerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerResponse>): RunnerResponse {
    const message = createBaseRunnerResponse();
    message.runner = (object.runner !== undefined && object.runner !== null)
      ? Item4.fromPartial(object.runner)
      : undefined;
    return message;
  },
};

function createBaseRunnersRequest(): RunnersRequest {
  return { jobId: undefined, versionId: undefined, actionId: undefined, status: undefined };
}

export const RunnersRequest: MessageFns<RunnersRequest> = {
  encode(message: RunnersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== undefined) {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    if (message.actionId !== undefined) {
      writer.uint32(26).string(message.actionId);
    }
    if (message.status !== undefined) {
      writer.uint32(32).int32(item_StatusToNumber(message.status));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = item_StatusFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnersRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : undefined,
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : undefined,
      status: isSet(object.status) ? item_StatusFromJSON(object.status) : undefined,
    };
  },

  toJSON(message: RunnersRequest): unknown {
    const obj: any = {};
    if (message.jobId !== undefined) {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.actionId !== undefined) {
      obj.actionId = message.actionId;
    }
    if (message.status !== undefined) {
      obj.status = item_StatusToJSON(message.status);
    }
    return obj;
  },

  create(base?: DeepPartial<RunnersRequest>): RunnersRequest {
    return RunnersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnersRequest>): RunnersRequest {
    const message = createBaseRunnersRequest();
    message.jobId = object.jobId ?? undefined;
    message.versionId = object.versionId ?? undefined;
    message.actionId = object.actionId ?? undefined;
    message.status = object.status ?? undefined;
    return message;
  },
};

function createBaseRunnersResponse(): RunnersResponse {
  return { runners: [] };
}

export const RunnersResponse: MessageFns<RunnersResponse> = {
  encode(message: RunnersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.runners) {
      Item4.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runners.push(Item4.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnersResponse {
    return {
      runners: globalThis.Array.isArray(object?.runners) ? object.runners.map((e: any) => Item4.fromJSON(e)) : [],
    };
  },

  toJSON(message: RunnersResponse): unknown {
    const obj: any = {};
    if (message.runners?.length) {
      obj.runners = message.runners.map((e) => Item4.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RunnersResponse>): RunnersResponse {
    return RunnersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnersResponse>): RunnersResponse {
    const message = createBaseRunnersResponse();
    message.runners = object.runners?.map((e) => Item4.fromPartial(e)) || [];
    return message;
  },
};

export type GeneralAPIDefinition = typeof GeneralAPIDefinition;
export const GeneralAPIDefinition = {
  name: "GeneralAPI",
  fullName: "GeneralAPI.GeneralAPI",
  methods: {
    getJob: {
      name: "getJob",
      requestType: JobRequest,
      requestStream: false,
      responseType: JobResponse,
      responseStream: false,
      options: {},
    },
    getJobs: {
      name: "getJobs",
      requestType: JobsRequest,
      requestStream: false,
      responseType: JobsResponse,
      responseStream: false,
      options: {},
    },
    getJobVersion: {
      name: "getJobVersion",
      requestType: JobVersionRequest,
      requestStream: false,
      responseType: JobVersionResponse,
      responseStream: false,
      options: {},
    },
    getJobVersions: {
      name: "getJobVersions",
      requestType: JobVersionsRequest,
      requestStream: false,
      responseType: JobVersionsResponse,
      responseStream: false,
      options: {},
    },
    getJobAction: {
      name: "getJobAction",
      requestType: JobActionRequest,
      requestStream: false,
      responseType: JobActionResponse,
      responseStream: false,
      options: {},
    },
    getJobActions: {
      name: "getJobActions",
      requestType: JobActionsRequest,
      requestStream: false,
      responseType: JobActionsResponse,
      responseStream: false,
      options: {},
    },
    getJobTrigger: {
      name: "getJobTrigger",
      requestType: JobTriggerRequest,
      requestStream: false,
      responseType: JobTriggerResponse,
      responseStream: false,
      options: {},
    },
    getJobTriggers: {
      name: "getJobTriggers",
      requestType: JobTriggersRequest,
      requestStream: false,
      responseType: JobTriggersResponse,
      responseStream: false,
      options: {},
    },
    getRunner: {
      name: "getRunner",
      requestType: RunnerRequest,
      requestStream: false,
      responseType: RunnerResponse,
      responseStream: false,
      options: {},
    },
    getRunners: {
      name: "getRunners",
      requestType: RunnersRequest,
      requestStream: false,
      responseType: RunnersResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface GeneralAPIServiceImplementation<CallContextExt = {}> {
  getJob(request: JobRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JobResponse>>;
  getJobs(request: JobsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JobsResponse>>;
  getJobVersion(
    request: JobVersionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobVersionResponse>>;
  getJobVersions(
    request: JobVersionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobVersionsResponse>>;
  getJobAction(
    request: JobActionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobActionResponse>>;
  getJobActions(
    request: JobActionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobActionsResponse>>;
  getJobTrigger(
    request: JobTriggerRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobTriggerResponse>>;
  getJobTriggers(
    request: JobTriggersRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<JobTriggersResponse>>;
  getRunner(request: RunnerRequest, context: CallContext & CallContextExt): Promise<DeepPartial<RunnerResponse>>;
  getRunners(request: RunnersRequest, context: CallContext & CallContextExt): Promise<DeepPartial<RunnersResponse>>;
}

export interface GeneralAPIClient<CallOptionsExt = {}> {
  getJob(request: DeepPartial<JobRequest>, options?: CallOptions & CallOptionsExt): Promise<JobResponse>;
  getJobs(request: DeepPartial<JobsRequest>, options?: CallOptions & CallOptionsExt): Promise<JobsResponse>;
  getJobVersion(
    request: DeepPartial<JobVersionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobVersionResponse>;
  getJobVersions(
    request: DeepPartial<JobVersionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobVersionsResponse>;
  getJobAction(
    request: DeepPartial<JobActionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobActionResponse>;
  getJobActions(
    request: DeepPartial<JobActionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobActionsResponse>;
  getJobTrigger(
    request: DeepPartial<JobTriggerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobTriggerResponse>;
  getJobTriggers(
    request: DeepPartial<JobTriggersRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<JobTriggersResponse>;
  getRunner(request: DeepPartial<RunnerRequest>, options?: CallOptions & CallOptionsExt): Promise<RunnerResponse>;
  getRunners(request: DeepPartial<RunnersRequest>, options?: CallOptions & CallOptionsExt): Promise<RunnersResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
