// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: runner.proto

/* eslint-disable */

export const protobufPackage = "RunnerAPI";

export type RunnerAPIDefinition = typeof RunnerAPIDefinition;
export const RunnerAPIDefinition = { name: "RunnerAPI", fullName: "RunnerAPI.RunnerAPI", methods: {} } as const;

export interface RunnerAPIServiceImplementation<CallContextExt = {}> {
}

export interface RunnerAPIClient<CallOptionsExt = {}> {
}
