// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: server.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "Server";

export const JobStatus = { ENABLED: "ENABLED", DISABLED: "DISABLED", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type JobStatus = typeof JobStatus[keyof typeof JobStatus];

export namespace JobStatus {
  export type ENABLED = typeof JobStatus.ENABLED;
  export type DISABLED = typeof JobStatus.DISABLED;
  export type UNRECOGNIZED = typeof JobStatus.UNRECOGNIZED;
}

export function jobStatusFromJSON(object: any): JobStatus {
  switch (object) {
    case 0:
    case "ENABLED":
      return JobStatus.ENABLED;
    case 1:
    case "DISABLED":
      return JobStatus.DISABLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JobStatus.UNRECOGNIZED;
  }
}

export function jobStatusToJSON(object: JobStatus): string {
  switch (object) {
    case JobStatus.ENABLED:
      return "ENABLED";
    case JobStatus.DISABLED:
      return "DISABLED";
    case JobStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function jobStatusToNumber(object: JobStatus): number {
  switch (object) {
    case JobStatus.ENABLED:
      return 0;
    case JobStatus.DISABLED:
      return 1;
    case JobStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export const ActionRunnerMode = { STANDARD: "STANDARD", RUN_ONCE: "RUN_ONCE", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type ActionRunnerMode = typeof ActionRunnerMode[keyof typeof ActionRunnerMode];

export namespace ActionRunnerMode {
  export type STANDARD = typeof ActionRunnerMode.STANDARD;
  export type RUN_ONCE = typeof ActionRunnerMode.RUN_ONCE;
  export type UNRECOGNIZED = typeof ActionRunnerMode.UNRECOGNIZED;
}

export function actionRunnerModeFromJSON(object: any): ActionRunnerMode {
  switch (object) {
    case 0:
    case "STANDARD":
      return ActionRunnerMode.STANDARD;
    case 1:
    case "RUN_ONCE":
      return ActionRunnerMode.RUN_ONCE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActionRunnerMode.UNRECOGNIZED;
  }
}

export function actionRunnerModeToJSON(object: ActionRunnerMode): string {
  switch (object) {
    case ActionRunnerMode.STANDARD:
      return "STANDARD";
    case ActionRunnerMode.RUN_ONCE:
      return "RUN_ONCE";
    case ActionRunnerMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function actionRunnerModeToNumber(object: ActionRunnerMode): number {
  switch (object) {
    case ActionRunnerMode.STANDARD:
      return 0;
    case ActionRunnerMode.RUN_ONCE:
      return 1;
    case ActionRunnerMode.UNRECOGNIZED:
    default:
      return -1;
  }
}

export const RunnerStatus = {
  STARTING: "STARTING",
  READY: "READY",
  CLOSING: "CLOSING",
  CLOSED: "CLOSED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type RunnerStatus = typeof RunnerStatus[keyof typeof RunnerStatus];

export namespace RunnerStatus {
  export type STARTING = typeof RunnerStatus.STARTING;
  export type READY = typeof RunnerStatus.READY;
  export type CLOSING = typeof RunnerStatus.CLOSING;
  export type CLOSED = typeof RunnerStatus.CLOSED;
  export type UNRECOGNIZED = typeof RunnerStatus.UNRECOGNIZED;
}

export function runnerStatusFromJSON(object: any): RunnerStatus {
  switch (object) {
    case 0:
    case "STARTING":
      return RunnerStatus.STARTING;
    case 1:
    case "READY":
      return RunnerStatus.READY;
    case 2:
    case "CLOSING":
      return RunnerStatus.CLOSING;
    case 3:
    case "CLOSED":
      return RunnerStatus.CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RunnerStatus.UNRECOGNIZED;
  }
}

export function runnerStatusToJSON(object: RunnerStatus): string {
  switch (object) {
    case RunnerStatus.STARTING:
      return "STARTING";
    case RunnerStatus.READY:
      return "READY";
    case RunnerStatus.CLOSING:
      return "CLOSING";
    case RunnerStatus.CLOSED:
      return "CLOSED";
    case RunnerStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function runnerStatusToNumber(object: RunnerStatus): number {
  switch (object) {
    case RunnerStatus.STARTING:
      return 0;
    case RunnerStatus.READY:
      return 1;
    case RunnerStatus.CLOSING:
      return 2;
    case RunnerStatus.CLOSED:
      return 3;
    case RunnerStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Empty {
}

export interface ExportChunk {
  id: string;
  sequence: number;
  data: Uint8Array;
}

export interface GetJobRequest {
  id: string;
}

export interface GetActionRequest {
  jobId: string;
  versionId?: string | undefined;
  actionId?: string | undefined;
}

export interface GetTriggerRequest {
  jobId: string;
  versionId?: string | undefined;
  triggerId?: string | undefined;
}

export interface GetRunnersRequest {
  jobId?: string | undefined;
  versionId?: string | undefined;
  actionId?: string | undefined;
}

export interface CreateRunnerRequest {
  jobId: string;
  versionId: string;
}

export interface PublicKeysResponse {
  publicKeys: string[];
}

export interface JwtRequest {
  token: string;
  scopes: string[];
}

export interface JwtResponse {
  jwt: string;
}

export interface GetGatewayConfigResponse {
  items: GetGatewayConfigResponse_Item[];
}

export interface GetGatewayConfigResponse_Item {
  job: JobItem | undefined;
  action: ActionItem | undefined;
  httpTriggers: TriggerHttpItem[];
  runners: RunnerItem[];
}

export interface JobItem {
  id: string;
  jobName: string;
  versionId?: string | undefined;
  status: JobStatus;
}

export interface ActionItem {
  id: string;
  runnerAsynchronous: boolean;
  runnerMinCount: number;
  runnerMaxCount: number;
  runnerTimeout: number;
  runnerMaxIdleAge: number;
  runnerMaxAge: number;
  runnerMaxAgeHard: number;
  runnerMode: ActionRunnerMode;
}

export interface TriggerHttpItem {
  id: string;
  jobId: string;
  jobVersionId: string;
  name?: string | undefined;
  method?: string | undefined;
  hostname?: string | undefined;
  path?: string | undefined;
  createdAt: number;
}

export interface TriggerMqttItem {
  id: string;
  jobId: string;
  jobVersionId: string;
  name?: string | undefined;
  topics: string[];
  protocol?: string | undefined;
  port?: string | undefined;
  host?: string | undefined;
  username?: string | undefined;
  password?: string | undefined;
  clientId?: string | undefined;
  createdAt: number;
}

export interface TriggerScheduleItem {
  id: string;
  jobId: string;
  jobVersionId: string;
  name?: string | undefined;
  cron: string;
  timezone?: string | undefined;
  createdAt: number;
}

export interface RunnerItem {
  id: string;
  jobId: string;
  jobVersionId: string;
  actionId: string;
  status: RunnerStatus;
  ip: string;
  hostname: string;
  port: number;
  createdAt: number;
  readyAt?: number | undefined;
  closingAt?: number | undefined;
  closedAt?: number | undefined;
}

export interface StoreGetRequest {
  key: string;
}

export interface StoreSetRequest {
  key: string;
  value: string;
  ttl: number;
}

export interface StoreDeleteRequest {
  key: string;
}

export interface StoreItem {
  key: string;
  value: string;
  expiry: number;
  createdAt: number;
  modified: number;
}

export interface MqttPublishRequest {
  topic: string;
  payload: Uint8Array;
}

export interface InitRequest {
  token: string;
}

export interface InitResponse {
}

export const InitResponse_Status = {
  SUCCESS: "SUCCESS",
  FAILURE_GENERIC: "FAILURE_GENERIC",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type InitResponse_Status = typeof InitResponse_Status[keyof typeof InitResponse_Status];

export namespace InitResponse_Status {
  export type SUCCESS = typeof InitResponse_Status.SUCCESS;
  export type FAILURE_GENERIC = typeof InitResponse_Status.FAILURE_GENERIC;
  export type UNRECOGNIZED = typeof InitResponse_Status.UNRECOGNIZED;
}

export function initResponse_StatusFromJSON(object: any): InitResponse_Status {
  switch (object) {
    case 0:
    case "SUCCESS":
      return InitResponse_Status.SUCCESS;
    case 1:
    case "FAILURE_GENERIC":
      return InitResponse_Status.FAILURE_GENERIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InitResponse_Status.UNRECOGNIZED;
  }
}

export function initResponse_StatusToJSON(object: InitResponse_Status): string {
  switch (object) {
    case InitResponse_Status.SUCCESS:
      return "SUCCESS";
    case InitResponse_Status.FAILURE_GENERIC:
      return "FAILURE_GENERIC";
    case InitResponse_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function initResponse_StatusToNumber(object: InitResponse_Status): number {
  switch (object) {
    case InitResponse_Status.SUCCESS:
      return 0;
    case InitResponse_Status.FAILURE_GENERIC:
      return 1;
    case InitResponse_Status.UNRECOGNIZED:
    default:
      return -1;
  }
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<Empty>): Empty {
    return Empty.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<Empty>): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseExportChunk(): ExportChunk {
  return { id: "", sequence: 0, data: new Uint8Array(0) };
}

export const ExportChunk: MessageFns<ExportChunk> = {
  encode(message: ExportChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.sequence !== 0) {
      writer.uint32(16).int64(message.sequence);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExportChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sequence = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportChunk {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: ExportChunk): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create(base?: DeepPartial<ExportChunk>): ExportChunk {
    return ExportChunk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExportChunk>): ExportChunk {
    const message = createBaseExportChunk();
    message.id = object.id ?? "";
    message.sequence = object.sequence ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseGetJobRequest(): GetJobRequest {
  return { id: "" };
}

export const GetJobRequest: MessageFns<GetJobRequest> = {
  encode(message: GetJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetJobRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetJobRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<GetJobRequest>): GetJobRequest {
    return GetJobRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetJobRequest>): GetJobRequest {
    const message = createBaseGetJobRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetActionRequest(): GetActionRequest {
  return { jobId: "", versionId: undefined, actionId: undefined };
}

export const GetActionRequest: MessageFns<GetActionRequest> = {
  encode(message: GetActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    if (message.actionId !== undefined) {
      writer.uint32(26).string(message.actionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetActionRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : undefined,
    };
  },

  toJSON(message: GetActionRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.actionId !== undefined) {
      obj.actionId = message.actionId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetActionRequest>): GetActionRequest {
    return GetActionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetActionRequest>): GetActionRequest {
    const message = createBaseGetActionRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? undefined;
    message.actionId = object.actionId ?? undefined;
    return message;
  },
};

function createBaseGetTriggerRequest(): GetTriggerRequest {
  return { jobId: "", versionId: undefined, triggerId: undefined };
}

export const GetTriggerRequest: MessageFns<GetTriggerRequest> = {
  encode(message: GetTriggerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    if (message.triggerId !== undefined) {
      writer.uint32(26).string(message.triggerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTriggerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTriggerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.triggerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTriggerRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      triggerId: isSet(object.triggerId) ? globalThis.String(object.triggerId) : undefined,
    };
  },

  toJSON(message: GetTriggerRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.triggerId !== undefined) {
      obj.triggerId = message.triggerId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetTriggerRequest>): GetTriggerRequest {
    return GetTriggerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTriggerRequest>): GetTriggerRequest {
    const message = createBaseGetTriggerRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? undefined;
    message.triggerId = object.triggerId ?? undefined;
    return message;
  },
};

function createBaseGetRunnersRequest(): GetRunnersRequest {
  return { jobId: undefined, versionId: undefined, actionId: undefined };
}

export const GetRunnersRequest: MessageFns<GetRunnersRequest> = {
  encode(message: GetRunnersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== undefined) {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== undefined) {
      writer.uint32(18).string(message.versionId);
    }
    if (message.actionId !== undefined) {
      writer.uint32(26).string(message.actionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRunnersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRunnersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRunnersRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : undefined,
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : undefined,
    };
  },

  toJSON(message: GetRunnersRequest): unknown {
    const obj: any = {};
    if (message.jobId !== undefined) {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.actionId !== undefined) {
      obj.actionId = message.actionId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetRunnersRequest>): GetRunnersRequest {
    return GetRunnersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetRunnersRequest>): GetRunnersRequest {
    const message = createBaseGetRunnersRequest();
    message.jobId = object.jobId ?? undefined;
    message.versionId = object.versionId ?? undefined;
    message.actionId = object.actionId ?? undefined;
    return message;
  },
};

function createBaseCreateRunnerRequest(): CreateRunnerRequest {
  return { jobId: "", versionId: "" };
}

export const CreateRunnerRequest: MessageFns<CreateRunnerRequest> = {
  encode(message: CreateRunnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.versionId !== "") {
      writer.uint32(18).string(message.versionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRunnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRunnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRunnerRequest {
    return {
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : "",
    };
  },

  toJSON(message: CreateRunnerRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== "") {
      obj.versionId = message.versionId;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateRunnerRequest>): CreateRunnerRequest {
    return CreateRunnerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateRunnerRequest>): CreateRunnerRequest {
    const message = createBaseCreateRunnerRequest();
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? "";
    return message;
  },
};

function createBasePublicKeysResponse(): PublicKeysResponse {
  return { publicKeys: [] };
}

export const PublicKeysResponse: MessageFns<PublicKeysResponse> = {
  encode(message: PublicKeysResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.publicKeys) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublicKeysResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublicKeysResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publicKeys.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublicKeysResponse {
    return {
      publicKeys: globalThis.Array.isArray(object?.publicKeys)
        ? object.publicKeys.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: PublicKeysResponse): unknown {
    const obj: any = {};
    if (message.publicKeys?.length) {
      obj.publicKeys = message.publicKeys;
    }
    return obj;
  },

  create(base?: DeepPartial<PublicKeysResponse>): PublicKeysResponse {
    return PublicKeysResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PublicKeysResponse>): PublicKeysResponse {
    const message = createBasePublicKeysResponse();
    message.publicKeys = object.publicKeys?.map((e) => e) || [];
    return message;
  },
};

function createBaseJwtRequest(): JwtRequest {
  return { token: "", scopes: [] };
}

export const JwtRequest: MessageFns<JwtRequest> = {
  encode(message: JwtRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    for (const v of message.scopes) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JwtRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJwtRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JwtRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: JwtRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    return obj;
  },

  create(base?: DeepPartial<JwtRequest>): JwtRequest {
    return JwtRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JwtRequest>): JwtRequest {
    const message = createBaseJwtRequest();
    message.token = object.token ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    return message;
  },
};

function createBaseJwtResponse(): JwtResponse {
  return { jwt: "" };
}

export const JwtResponse: MessageFns<JwtResponse> = {
  encode(message: JwtResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jwt !== "") {
      writer.uint32(10).string(message.jwt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JwtResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJwtResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jwt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JwtResponse {
    return { jwt: isSet(object.jwt) ? globalThis.String(object.jwt) : "" };
  },

  toJSON(message: JwtResponse): unknown {
    const obj: any = {};
    if (message.jwt !== "") {
      obj.jwt = message.jwt;
    }
    return obj;
  },

  create(base?: DeepPartial<JwtResponse>): JwtResponse {
    return JwtResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JwtResponse>): JwtResponse {
    const message = createBaseJwtResponse();
    message.jwt = object.jwt ?? "";
    return message;
  },
};

function createBaseGetGatewayConfigResponse(): GetGatewayConfigResponse {
  return { items: [] };
}

export const GetGatewayConfigResponse: MessageFns<GetGatewayConfigResponse> = {
  encode(message: GetGatewayConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      GetGatewayConfigResponse_Item.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGatewayConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGatewayConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(GetGatewayConfigResponse_Item.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGatewayConfigResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => GetGatewayConfigResponse_Item.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetGatewayConfigResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => GetGatewayConfigResponse_Item.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetGatewayConfigResponse>): GetGatewayConfigResponse {
    return GetGatewayConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetGatewayConfigResponse>): GetGatewayConfigResponse {
    const message = createBaseGetGatewayConfigResponse();
    message.items = object.items?.map((e) => GetGatewayConfigResponse_Item.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetGatewayConfigResponse_Item(): GetGatewayConfigResponse_Item {
  return { job: undefined, action: undefined, httpTriggers: [], runners: [] };
}

export const GetGatewayConfigResponse_Item: MessageFns<GetGatewayConfigResponse_Item> = {
  encode(message: GetGatewayConfigResponse_Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.job !== undefined) {
      JobItem.encode(message.job, writer.uint32(10).fork()).join();
    }
    if (message.action !== undefined) {
      ActionItem.encode(message.action, writer.uint32(18).fork()).join();
    }
    for (const v of message.httpTriggers) {
      TriggerHttpItem.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.runners) {
      RunnerItem.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGatewayConfigResponse_Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGatewayConfigResponse_Item();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.job = JobItem.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.action = ActionItem.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.httpTriggers.push(TriggerHttpItem.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.runners.push(RunnerItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGatewayConfigResponse_Item {
    return {
      job: isSet(object.job) ? JobItem.fromJSON(object.job) : undefined,
      action: isSet(object.action) ? ActionItem.fromJSON(object.action) : undefined,
      httpTriggers: globalThis.Array.isArray(object?.httpTriggers)
        ? object.httpTriggers.map((e: any) => TriggerHttpItem.fromJSON(e))
        : [],
      runners: globalThis.Array.isArray(object?.runners) ? object.runners.map((e: any) => RunnerItem.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetGatewayConfigResponse_Item): unknown {
    const obj: any = {};
    if (message.job !== undefined) {
      obj.job = JobItem.toJSON(message.job);
    }
    if (message.action !== undefined) {
      obj.action = ActionItem.toJSON(message.action);
    }
    if (message.httpTriggers?.length) {
      obj.httpTriggers = message.httpTriggers.map((e) => TriggerHttpItem.toJSON(e));
    }
    if (message.runners?.length) {
      obj.runners = message.runners.map((e) => RunnerItem.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetGatewayConfigResponse_Item>): GetGatewayConfigResponse_Item {
    return GetGatewayConfigResponse_Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetGatewayConfigResponse_Item>): GetGatewayConfigResponse_Item {
    const message = createBaseGetGatewayConfigResponse_Item();
    message.job = (object.job !== undefined && object.job !== null) ? JobItem.fromPartial(object.job) : undefined;
    message.action = (object.action !== undefined && object.action !== null)
      ? ActionItem.fromPartial(object.action)
      : undefined;
    message.httpTriggers = object.httpTriggers?.map((e) => TriggerHttpItem.fromPartial(e)) || [];
    message.runners = object.runners?.map((e) => RunnerItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseJobItem(): JobItem {
  return { id: "", jobName: "", versionId: undefined, status: JobStatus.ENABLED };
}

export const JobItem: MessageFns<JobItem> = {
  encode(message: JobItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobName !== "") {
      writer.uint32(18).string(message.jobName);
    }
    if (message.versionId !== undefined) {
      writer.uint32(26).string(message.versionId);
    }
    if (message.status !== JobStatus.ENABLED) {
      writer.uint32(32).int32(jobStatusToNumber(message.status));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = jobStatusFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobName: isSet(object.jobName) ? globalThis.String(object.jobName) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      status: isSet(object.status) ? jobStatusFromJSON(object.status) : JobStatus.ENABLED,
    };
  },

  toJSON(message: JobItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobName !== "") {
      obj.jobName = message.jobName;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.status !== JobStatus.ENABLED) {
      obj.status = jobStatusToJSON(message.status);
    }
    return obj;
  },

  create(base?: DeepPartial<JobItem>): JobItem {
    return JobItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobItem>): JobItem {
    const message = createBaseJobItem();
    message.id = object.id ?? "";
    message.jobName = object.jobName ?? "";
    message.versionId = object.versionId ?? undefined;
    message.status = object.status ?? JobStatus.ENABLED;
    return message;
  },
};

function createBaseActionItem(): ActionItem {
  return {
    id: "",
    runnerAsynchronous: false,
    runnerMinCount: 0,
    runnerMaxCount: 0,
    runnerTimeout: 0,
    runnerMaxIdleAge: 0,
    runnerMaxAge: 0,
    runnerMaxAgeHard: 0,
    runnerMode: ActionRunnerMode.STANDARD,
  };
}

export const ActionItem: MessageFns<ActionItem> = {
  encode(message: ActionItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.runnerAsynchronous !== false) {
      writer.uint32(16).bool(message.runnerAsynchronous);
    }
    if (message.runnerMinCount !== 0) {
      writer.uint32(24).uint32(message.runnerMinCount);
    }
    if (message.runnerMaxCount !== 0) {
      writer.uint32(32).uint32(message.runnerMaxCount);
    }
    if (message.runnerTimeout !== 0) {
      writer.uint32(40).uint32(message.runnerTimeout);
    }
    if (message.runnerMaxIdleAge !== 0) {
      writer.uint32(48).uint32(message.runnerMaxIdleAge);
    }
    if (message.runnerMaxAge !== 0) {
      writer.uint32(56).uint32(message.runnerMaxAge);
    }
    if (message.runnerMaxAgeHard !== 0) {
      writer.uint32(64).uint32(message.runnerMaxAgeHard);
    }
    if (message.runnerMode !== ActionRunnerMode.STANDARD) {
      writer.uint32(72).int32(actionRunnerModeToNumber(message.runnerMode));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.runnerAsynchronous = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.runnerMinCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.runnerMaxCount = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.runnerTimeout = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.runnerMaxIdleAge = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.runnerMaxAge = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.runnerMaxAgeHard = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.runnerMode = actionRunnerModeFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      runnerAsynchronous: isSet(object.runnerAsynchronous) ? globalThis.Boolean(object.runnerAsynchronous) : false,
      runnerMinCount: isSet(object.runnerMinCount) ? globalThis.Number(object.runnerMinCount) : 0,
      runnerMaxCount: isSet(object.runnerMaxCount) ? globalThis.Number(object.runnerMaxCount) : 0,
      runnerTimeout: isSet(object.runnerTimeout) ? globalThis.Number(object.runnerTimeout) : 0,
      runnerMaxIdleAge: isSet(object.runnerMaxIdleAge) ? globalThis.Number(object.runnerMaxIdleAge) : 0,
      runnerMaxAge: isSet(object.runnerMaxAge) ? globalThis.Number(object.runnerMaxAge) : 0,
      runnerMaxAgeHard: isSet(object.runnerMaxAgeHard) ? globalThis.Number(object.runnerMaxAgeHard) : 0,
      runnerMode: isSet(object.runnerMode) ? actionRunnerModeFromJSON(object.runnerMode) : ActionRunnerMode.STANDARD,
    };
  },

  toJSON(message: ActionItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.runnerAsynchronous !== false) {
      obj.runnerAsynchronous = message.runnerAsynchronous;
    }
    if (message.runnerMinCount !== 0) {
      obj.runnerMinCount = Math.round(message.runnerMinCount);
    }
    if (message.runnerMaxCount !== 0) {
      obj.runnerMaxCount = Math.round(message.runnerMaxCount);
    }
    if (message.runnerTimeout !== 0) {
      obj.runnerTimeout = Math.round(message.runnerTimeout);
    }
    if (message.runnerMaxIdleAge !== 0) {
      obj.runnerMaxIdleAge = Math.round(message.runnerMaxIdleAge);
    }
    if (message.runnerMaxAge !== 0) {
      obj.runnerMaxAge = Math.round(message.runnerMaxAge);
    }
    if (message.runnerMaxAgeHard !== 0) {
      obj.runnerMaxAgeHard = Math.round(message.runnerMaxAgeHard);
    }
    if (message.runnerMode !== ActionRunnerMode.STANDARD) {
      obj.runnerMode = actionRunnerModeToJSON(message.runnerMode);
    }
    return obj;
  },

  create(base?: DeepPartial<ActionItem>): ActionItem {
    return ActionItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ActionItem>): ActionItem {
    const message = createBaseActionItem();
    message.id = object.id ?? "";
    message.runnerAsynchronous = object.runnerAsynchronous ?? false;
    message.runnerMinCount = object.runnerMinCount ?? 0;
    message.runnerMaxCount = object.runnerMaxCount ?? 0;
    message.runnerTimeout = object.runnerTimeout ?? 0;
    message.runnerMaxIdleAge = object.runnerMaxIdleAge ?? 0;
    message.runnerMaxAge = object.runnerMaxAge ?? 0;
    message.runnerMaxAgeHard = object.runnerMaxAgeHard ?? 0;
    message.runnerMode = object.runnerMode ?? ActionRunnerMode.STANDARD;
    return message;
  },
};

function createBaseTriggerHttpItem(): TriggerHttpItem {
  return {
    id: "",
    jobId: "",
    jobVersionId: "",
    name: undefined,
    method: undefined,
    hostname: undefined,
    path: undefined,
    createdAt: 0,
  };
}

export const TriggerHttpItem: MessageFns<TriggerHttpItem> = {
  encode(message: TriggerHttpItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.jobVersionId !== "") {
      writer.uint32(26).string(message.jobVersionId);
    }
    if (message.name !== undefined) {
      writer.uint32(34).string(message.name);
    }
    if (message.method !== undefined) {
      writer.uint32(42).string(message.method);
    }
    if (message.hostname !== undefined) {
      writer.uint32(50).string(message.hostname);
    }
    if (message.path !== undefined) {
      writer.uint32(58).string(message.path);
    }
    if (message.createdAt !== 0) {
      writer.uint32(64).uint64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerHttpItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerHttpItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerHttpItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      method: isSet(object.method) ? globalThis.String(object.method) : undefined,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : undefined,
      path: isSet(object.path) ? globalThis.String(object.path) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: TriggerHttpItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.method !== undefined) {
      obj.method = message.method;
    }
    if (message.hostname !== undefined) {
      obj.hostname = message.hostname;
    }
    if (message.path !== undefined) {
      obj.path = message.path;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create(base?: DeepPartial<TriggerHttpItem>): TriggerHttpItem {
    return TriggerHttpItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TriggerHttpItem>): TriggerHttpItem {
    const message = createBaseTriggerHttpItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.jobVersionId = object.jobVersionId ?? "";
    message.name = object.name ?? undefined;
    message.method = object.method ?? undefined;
    message.hostname = object.hostname ?? undefined;
    message.path = object.path ?? undefined;
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBaseTriggerMqttItem(): TriggerMqttItem {
  return {
    id: "",
    jobId: "",
    jobVersionId: "",
    name: undefined,
    topics: [],
    protocol: undefined,
    port: undefined,
    host: undefined,
    username: undefined,
    password: undefined,
    clientId: undefined,
    createdAt: 0,
  };
}

export const TriggerMqttItem: MessageFns<TriggerMqttItem> = {
  encode(message: TriggerMqttItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.jobVersionId !== "") {
      writer.uint32(26).string(message.jobVersionId);
    }
    if (message.name !== undefined) {
      writer.uint32(34).string(message.name);
    }
    for (const v of message.topics) {
      writer.uint32(42).string(v!);
    }
    if (message.protocol !== undefined) {
      writer.uint32(50).string(message.protocol);
    }
    if (message.port !== undefined) {
      writer.uint32(58).string(message.port);
    }
    if (message.host !== undefined) {
      writer.uint32(66).string(message.host);
    }
    if (message.username !== undefined) {
      writer.uint32(74).string(message.username);
    }
    if (message.password !== undefined) {
      writer.uint32(82).string(message.password);
    }
    if (message.clientId !== undefined) {
      writer.uint32(90).string(message.clientId);
    }
    if (message.createdAt !== 0) {
      writer.uint32(96).uint64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerMqttItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerMqttItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.topics.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.protocol = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.port = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerMqttItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      topics: globalThis.Array.isArray(object?.topics) ? object.topics.map((e: any) => globalThis.String(e)) : [],
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : undefined,
      port: isSet(object.port) ? globalThis.String(object.port) : undefined,
      host: isSet(object.host) ? globalThis.String(object.host) : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : undefined,
      password: isSet(object.password) ? globalThis.String(object.password) : undefined,
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: TriggerMqttItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.topics?.length) {
      obj.topics = message.topics;
    }
    if (message.protocol !== undefined) {
      obj.protocol = message.protocol;
    }
    if (message.port !== undefined) {
      obj.port = message.port;
    }
    if (message.host !== undefined) {
      obj.host = message.host;
    }
    if (message.username !== undefined) {
      obj.username = message.username;
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    if (message.clientId !== undefined) {
      obj.clientId = message.clientId;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create(base?: DeepPartial<TriggerMqttItem>): TriggerMqttItem {
    return TriggerMqttItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TriggerMqttItem>): TriggerMqttItem {
    const message = createBaseTriggerMqttItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.jobVersionId = object.jobVersionId ?? "";
    message.name = object.name ?? undefined;
    message.topics = object.topics?.map((e) => e) || [];
    message.protocol = object.protocol ?? undefined;
    message.port = object.port ?? undefined;
    message.host = object.host ?? undefined;
    message.username = object.username ?? undefined;
    message.password = object.password ?? undefined;
    message.clientId = object.clientId ?? undefined;
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBaseTriggerScheduleItem(): TriggerScheduleItem {
  return { id: "", jobId: "", jobVersionId: "", name: undefined, cron: "", timezone: undefined, createdAt: 0 };
}

export const TriggerScheduleItem: MessageFns<TriggerScheduleItem> = {
  encode(message: TriggerScheduleItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.jobVersionId !== "") {
      writer.uint32(26).string(message.jobVersionId);
    }
    if (message.name !== undefined) {
      writer.uint32(34).string(message.name);
    }
    if (message.cron !== "") {
      writer.uint32(42).string(message.cron);
    }
    if (message.timezone !== undefined) {
      writer.uint32(50).string(message.timezone);
    }
    if (message.createdAt !== 0) {
      writer.uint32(56).uint64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerScheduleItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerScheduleItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cron = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerScheduleItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      cron: isSet(object.cron) ? globalThis.String(object.cron) : "",
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: TriggerScheduleItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.cron !== "") {
      obj.cron = message.cron;
    }
    if (message.timezone !== undefined) {
      obj.timezone = message.timezone;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create(base?: DeepPartial<TriggerScheduleItem>): TriggerScheduleItem {
    return TriggerScheduleItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TriggerScheduleItem>): TriggerScheduleItem {
    const message = createBaseTriggerScheduleItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.jobVersionId = object.jobVersionId ?? "";
    message.name = object.name ?? undefined;
    message.cron = object.cron ?? "";
    message.timezone = object.timezone ?? undefined;
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBaseRunnerItem(): RunnerItem {
  return {
    id: "",
    jobId: "",
    jobVersionId: "",
    actionId: "",
    status: RunnerStatus.STARTING,
    ip: "",
    hostname: "",
    port: 0,
    createdAt: 0,
    readyAt: undefined,
    closingAt: undefined,
    closedAt: undefined,
  };
}

export const RunnerItem: MessageFns<RunnerItem> = {
  encode(message: RunnerItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.jobVersionId !== "") {
      writer.uint32(26).string(message.jobVersionId);
    }
    if (message.actionId !== "") {
      writer.uint32(34).string(message.actionId);
    }
    if (message.status !== RunnerStatus.STARTING) {
      writer.uint32(40).int32(runnerStatusToNumber(message.status));
    }
    if (message.ip !== "") {
      writer.uint32(50).string(message.ip);
    }
    if (message.hostname !== "") {
      writer.uint32(58).string(message.hostname);
    }
    if (message.port !== 0) {
      writer.uint32(64).uint32(message.port);
    }
    if (message.createdAt !== 0) {
      writer.uint32(80).uint64(message.createdAt);
    }
    if (message.readyAt !== undefined) {
      writer.uint32(88).uint64(message.readyAt);
    }
    if (message.closingAt !== undefined) {
      writer.uint32(96).uint64(message.closingAt);
    }
    if (message.closedAt !== undefined) {
      writer.uint32(104).uint64(message.closedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jobVersionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = runnerStatusFromJSON(reader.int32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.readyAt = longToNumber(reader.uint64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.closingAt = longToNumber(reader.uint64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.closedAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunnerItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      jobVersionId: isSet(object.jobVersionId) ? globalThis.String(object.jobVersionId) : "",
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
      status: isSet(object.status) ? runnerStatusFromJSON(object.status) : RunnerStatus.STARTING,
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
      readyAt: isSet(object.readyAt) ? globalThis.Number(object.readyAt) : undefined,
      closingAt: isSet(object.closingAt) ? globalThis.Number(object.closingAt) : undefined,
      closedAt: isSet(object.closedAt) ? globalThis.Number(object.closedAt) : undefined,
    };
  },

  toJSON(message: RunnerItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.jobVersionId !== "") {
      obj.jobVersionId = message.jobVersionId;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.status !== RunnerStatus.STARTING) {
      obj.status = runnerStatusToJSON(message.status);
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.readyAt !== undefined) {
      obj.readyAt = Math.round(message.readyAt);
    }
    if (message.closingAt !== undefined) {
      obj.closingAt = Math.round(message.closingAt);
    }
    if (message.closedAt !== undefined) {
      obj.closedAt = Math.round(message.closedAt);
    }
    return obj;
  },

  create(base?: DeepPartial<RunnerItem>): RunnerItem {
    return RunnerItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerItem>): RunnerItem {
    const message = createBaseRunnerItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.jobVersionId = object.jobVersionId ?? "";
    message.actionId = object.actionId ?? "";
    message.status = object.status ?? RunnerStatus.STARTING;
    message.ip = object.ip ?? "";
    message.hostname = object.hostname ?? "";
    message.port = object.port ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.readyAt = object.readyAt ?? undefined;
    message.closingAt = object.closingAt ?? undefined;
    message.closedAt = object.closedAt ?? undefined;
    return message;
  },
};

function createBaseStoreGetRequest(): StoreGetRequest {
  return { key: "" };
}

export const StoreGetRequest: MessageFns<StoreGetRequest> = {
  encode(message: StoreGetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreGetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreGetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreGetRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: StoreGetRequest): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create(base?: DeepPartial<StoreGetRequest>): StoreGetRequest {
    return StoreGetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StoreGetRequest>): StoreGetRequest {
    const message = createBaseStoreGetRequest();
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseStoreSetRequest(): StoreSetRequest {
  return { key: "", value: "", ttl: 0 };
}

export const StoreSetRequest: MessageFns<StoreSetRequest> = {
  encode(message: StoreSetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    if (message.ttl !== 0) {
      writer.uint32(24).uint64(message.ttl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreSetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreSetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ttl = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreSetRequest {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : 0,
    };
  },

  toJSON(message: StoreSetRequest): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.ttl !== 0) {
      obj.ttl = Math.round(message.ttl);
    }
    return obj;
  },

  create(base?: DeepPartial<StoreSetRequest>): StoreSetRequest {
    return StoreSetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StoreSetRequest>): StoreSetRequest {
    const message = createBaseStoreSetRequest();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    message.ttl = object.ttl ?? 0;
    return message;
  },
};

function createBaseStoreDeleteRequest(): StoreDeleteRequest {
  return { key: "" };
}

export const StoreDeleteRequest: MessageFns<StoreDeleteRequest> = {
  encode(message: StoreDeleteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreDeleteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreDeleteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreDeleteRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: StoreDeleteRequest): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create(base?: DeepPartial<StoreDeleteRequest>): StoreDeleteRequest {
    return StoreDeleteRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StoreDeleteRequest>): StoreDeleteRequest {
    const message = createBaseStoreDeleteRequest();
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseStoreItem(): StoreItem {
  return { key: "", value: "", expiry: 0, createdAt: 0, modified: 0 };
}

export const StoreItem: MessageFns<StoreItem> = {
  encode(message: StoreItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    if (message.expiry !== 0) {
      writer.uint32(24).uint64(message.expiry);
    }
    if (message.createdAt !== 0) {
      writer.uint32(32).uint64(message.createdAt);
    }
    if (message.modified !== 0) {
      writer.uint32(40).uint64(message.modified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expiry = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.modified = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreItem {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      expiry: isSet(object.expiry) ? globalThis.Number(object.expiry) : 0,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
      modified: isSet(object.modified) ? globalThis.Number(object.modified) : 0,
    };
  },

  toJSON(message: StoreItem): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.expiry !== 0) {
      obj.expiry = Math.round(message.expiry);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.modified !== 0) {
      obj.modified = Math.round(message.modified);
    }
    return obj;
  },

  create(base?: DeepPartial<StoreItem>): StoreItem {
    return StoreItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StoreItem>): StoreItem {
    const message = createBaseStoreItem();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    message.expiry = object.expiry ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.modified = object.modified ?? 0;
    return message;
  },
};

function createBaseMqttPublishRequest(): MqttPublishRequest {
  return { topic: "", payload: new Uint8Array(0) };
}

export const MqttPublishRequest: MessageFns<MqttPublishRequest> = {
  encode(message: MqttPublishRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.topic !== "") {
      writer.uint32(10).string(message.topic);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MqttPublishRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMqttPublishRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MqttPublishRequest {
    return {
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: MqttPublishRequest): unknown {
    const obj: any = {};
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create(base?: DeepPartial<MqttPublishRequest>): MqttPublishRequest {
    return MqttPublishRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MqttPublishRequest>): MqttPublishRequest {
    const message = createBaseMqttPublishRequest();
    message.topic = object.topic ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseInitRequest(): InitRequest {
  return { token: "" };
}

export const InitRequest: MessageFns<InitRequest> = {
  encode(message: InitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InitRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: InitRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<InitRequest>): InitRequest {
    return InitRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<InitRequest>): InitRequest {
    const message = createBaseInitRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseInitResponse(): InitResponse {
  return {};
}

export const InitResponse: MessageFns<InitResponse> = {
  encode(_: InitResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InitResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInitResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): InitResponse {
    return {};
  },

  toJSON(_: InitResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<InitResponse>): InitResponse {
    return InitResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<InitResponse>): InitResponse {
    const message = createBaseInitResponse();
    return message;
  },
};

export type GeneralManagementDefinition = typeof GeneralManagementDefinition;
export const GeneralManagementDefinition = {
  name: "GeneralManagement",
  fullName: "Server.GeneralManagement",
  methods: {
    /** General */
    getJobs: {
      name: "getJobs",
      requestType: Empty,
      requestStream: false,
      responseType: JobItem,
      responseStream: true,
      options: {},
    },
    getJob: {
      name: "getJob",
      requestType: GetJobRequest,
      requestStream: false,
      responseType: JobItem,
      responseStream: false,
      options: {},
    },
    getAction: {
      name: "getAction",
      requestType: GetActionRequest,
      requestStream: false,
      responseType: ActionItem,
      responseStream: false,
      options: {},
    },
    getHttpTriggers: {
      name: "getHttpTriggers",
      requestType: GetTriggerRequest,
      requestStream: false,
      responseType: TriggerHttpItem,
      responseStream: true,
      options: {},
    },
    getMqttTriggers: {
      name: "getMqttTriggers",
      requestType: GetTriggerRequest,
      requestStream: false,
      responseType: TriggerMqttItem,
      responseStream: true,
      options: {},
    },
    getScheduleTriggers: {
      name: "getScheduleTriggers",
      requestType: GetTriggerRequest,
      requestStream: false,
      responseType: TriggerScheduleItem,
      responseStream: true,
      options: {},
    },
    getRunners: {
      name: "getRunners",
      requestType: GetRunnersRequest,
      requestStream: false,
      responseType: RunnerItem,
      responseStream: true,
      options: {},
    },
    /** Authentication related */
    getPublicKeys: {
      name: "getPublicKeys",
      requestType: Empty,
      requestStream: false,
      responseType: PublicKeysResponse,
      responseStream: false,
      options: {},
    },
    createJwt: {
      name: "createJwt",
      requestType: JwtRequest,
      requestStream: false,
      responseType: JwtResponse,
      responseStream: false,
      options: {},
    },
    /** Gateway Specific */
    createRunner: {
      name: "createRunner",
      requestType: CreateRunnerRequest,
      requestStream: false,
      responseType: RunnerItem,
      responseStream: false,
      options: {},
    },
    getGatewayConfig: {
      name: "getGatewayConfig",
      requestType: Empty,
      requestStream: false,
      responseType: GetGatewayConfigResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface GeneralManagementServiceImplementation<CallContextExt = {}> {
  /** General */
  getJobs(request: Empty, context: CallContext & CallContextExt): ServerStreamingMethodResult<DeepPartial<JobItem>>;
  getJob(request: GetJobRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JobItem>>;
  getAction(request: GetActionRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ActionItem>>;
  getHttpTriggers(
    request: GetTriggerRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<TriggerHttpItem>>;
  getMqttTriggers(
    request: GetTriggerRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<TriggerMqttItem>>;
  getScheduleTriggers(
    request: GetTriggerRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<TriggerScheduleItem>>;
  getRunners(
    request: GetRunnersRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<RunnerItem>>;
  /** Authentication related */
  getPublicKeys(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<PublicKeysResponse>>;
  createJwt(request: JwtRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JwtResponse>>;
  /** Gateway Specific */
  createRunner(request: CreateRunnerRequest, context: CallContext & CallContextExt): Promise<DeepPartial<RunnerItem>>;
  getGatewayConfig(
    request: Empty,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetGatewayConfigResponse>>;
}

export interface GeneralManagementClient<CallOptionsExt = {}> {
  /** General */
  getJobs(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<JobItem>;
  getJob(request: DeepPartial<GetJobRequest>, options?: CallOptions & CallOptionsExt): Promise<JobItem>;
  getAction(request: DeepPartial<GetActionRequest>, options?: CallOptions & CallOptionsExt): Promise<ActionItem>;
  getHttpTriggers(
    request: DeepPartial<GetTriggerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<TriggerHttpItem>;
  getMqttTriggers(
    request: DeepPartial<GetTriggerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<TriggerMqttItem>;
  getScheduleTriggers(
    request: DeepPartial<GetTriggerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<TriggerScheduleItem>;
  getRunners(
    request: DeepPartial<GetRunnersRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<RunnerItem>;
  /** Authentication related */
  getPublicKeys(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<PublicKeysResponse>;
  createJwt(request: DeepPartial<JwtRequest>, options?: CallOptions & CallOptionsExt): Promise<JwtResponse>;
  /** Gateway Specific */
  createRunner(request: DeepPartial<CreateRunnerRequest>, options?: CallOptions & CallOptionsExt): Promise<RunnerItem>;
  getGatewayConfig(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetGatewayConfigResponse>;
}

export type RunnerManagementDefinition = typeof RunnerManagementDefinition;
export const RunnerManagementDefinition = {
  name: "RunnerManagement",
  fullName: "Server.RunnerManagement",
  methods: {
    storeGet: {
      name: "storeGet",
      requestType: StoreGetRequest,
      requestStream: false,
      responseType: StoreItem,
      responseStream: false,
      options: {},
    },
    storeSet: {
      name: "storeSet",
      requestType: StoreSetRequest,
      requestStream: false,
      responseType: StoreItem,
      responseStream: false,
      options: {},
    },
    storeDelete: {
      name: "storeDelete",
      requestType: StoreDeleteRequest,
      requestStream: false,
      responseType: StoreItem,
      responseStream: false,
      options: {},
    },
    mqttPublish: {
      name: "mqttPublish",
      requestType: MqttPublishRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** Backend management methods */
    init: {
      name: "init",
      requestType: InitRequest,
      requestStream: false,
      responseType: InitResponse,
      responseStream: false,
      options: {},
    },
    archive: {
      name: "archive",
      requestType: Empty,
      requestStream: false,
      responseType: ExportChunk,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface RunnerManagementServiceImplementation<CallContextExt = {}> {
  storeGet(request: StoreGetRequest, context: CallContext & CallContextExt): Promise<DeepPartial<StoreItem>>;
  storeSet(request: StoreSetRequest, context: CallContext & CallContextExt): Promise<DeepPartial<StoreItem>>;
  storeDelete(request: StoreDeleteRequest, context: CallContext & CallContextExt): Promise<DeepPartial<StoreItem>>;
  mqttPublish(request: MqttPublishRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** Backend management methods */
  init(request: InitRequest, context: CallContext & CallContextExt): Promise<DeepPartial<InitResponse>>;
  archive(request: Empty, context: CallContext & CallContextExt): ServerStreamingMethodResult<DeepPartial<ExportChunk>>;
}

export interface RunnerManagementClient<CallOptionsExt = {}> {
  storeGet(request: DeepPartial<StoreGetRequest>, options?: CallOptions & CallOptionsExt): Promise<StoreItem>;
  storeSet(request: DeepPartial<StoreSetRequest>, options?: CallOptions & CallOptionsExt): Promise<StoreItem>;
  storeDelete(request: DeepPartial<StoreDeleteRequest>, options?: CallOptions & CallOptionsExt): Promise<StoreItem>;
  mqttPublish(request: DeepPartial<MqttPublishRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** Backend management methods */
  init(request: DeepPartial<InitRequest>, options?: CallOptions & CallOptionsExt): Promise<InitResponse>;
  archive(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<ExportChunk>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
