services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=jobber-username
      - POSTGRES_PASSWORD=jobber-password
      - POSTGRES_DB=jobber-database
    ports:
      - 5432:5432
