// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/action.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Action";

export interface Item {
  id: string;
  jobId: string;
  versionId: string;
  runnerImage: string;
  runnerAsynchronous: boolean;
  runnerMinCount: number;
  runnerMaxCount: number;
  runnerTimeout: number;
  runnerMaxIdleAge: number;
  runnerMaxAge: number;
  runnerMaxAgeHard: number;
  dockerArguments: Item_DockerArguments | undefined;
  runnerMode: Item_RunnerMode;
}

export const Item_RunnerMode = { STANDARD: "STANDARD", RUN_ONCE: "RUN_ONCE", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type Item_RunnerMode = typeof Item_RunnerMode[keyof typeof Item_RunnerMode];

export namespace Item_RunnerMode {
  export type STANDARD = typeof Item_RunnerMode.STANDARD;
  export type RUN_ONCE = typeof Item_RunnerMode.RUN_ONCE;
  export type UNRECOGNIZED = typeof Item_RunnerMode.UNRECOGNIZED;
}

export function item_RunnerModeFromJSON(object: any): Item_RunnerMode {
  switch (object) {
    case 0:
    case "STANDARD":
      return Item_RunnerMode.STANDARD;
    case 1:
    case "RUN_ONCE":
      return Item_RunnerMode.RUN_ONCE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Item_RunnerMode.UNRECOGNIZED;
  }
}

export function item_RunnerModeToJSON(object: Item_RunnerMode): string {
  switch (object) {
    case Item_RunnerMode.STANDARD:
      return "STANDARD";
    case Item_RunnerMode.RUN_ONCE:
      return "RUN_ONCE";
    case Item_RunnerMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function item_RunnerModeToNumber(object: Item_RunnerMode): number {
  switch (object) {
    case Item_RunnerMode.STANDARD:
      return 0;
    case Item_RunnerMode.RUN_ONCE:
      return 1;
    case Item_RunnerMode.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Item_DockerArguments {
  networks: string[];
  volumes: Item_DockerArguments_Volume[];
  labels: Item_DockerArguments_Label[];
  memoryLimit?: string | undefined;
  directPassthroughArguments: string[];
}

export interface Item_DockerArguments_Volume {
  source: string;
  target: string;
  mode: Item_DockerArguments_Volume_VolumeMode;
}

export const Item_DockerArguments_Volume_VolumeMode = {
  READ_ONLY: "READ_ONLY",
  READ_WRITE: "READ_WRITE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type Item_DockerArguments_Volume_VolumeMode =
  typeof Item_DockerArguments_Volume_VolumeMode[keyof typeof Item_DockerArguments_Volume_VolumeMode];

export namespace Item_DockerArguments_Volume_VolumeMode {
  export type READ_ONLY = typeof Item_DockerArguments_Volume_VolumeMode.READ_ONLY;
  export type READ_WRITE = typeof Item_DockerArguments_Volume_VolumeMode.READ_WRITE;
  export type UNRECOGNIZED = typeof Item_DockerArguments_Volume_VolumeMode.UNRECOGNIZED;
}

export function item_DockerArguments_Volume_VolumeModeFromJSON(object: any): Item_DockerArguments_Volume_VolumeMode {
  switch (object) {
    case 0:
    case "READ_ONLY":
      return Item_DockerArguments_Volume_VolumeMode.READ_ONLY;
    case 1:
    case "READ_WRITE":
      return Item_DockerArguments_Volume_VolumeMode.READ_WRITE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Item_DockerArguments_Volume_VolumeMode.UNRECOGNIZED;
  }
}

export function item_DockerArguments_Volume_VolumeModeToJSON(object: Item_DockerArguments_Volume_VolumeMode): string {
  switch (object) {
    case Item_DockerArguments_Volume_VolumeMode.READ_ONLY:
      return "READ_ONLY";
    case Item_DockerArguments_Volume_VolumeMode.READ_WRITE:
      return "READ_WRITE";
    case Item_DockerArguments_Volume_VolumeMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function item_DockerArguments_Volume_VolumeModeToNumber(object: Item_DockerArguments_Volume_VolumeMode): number {
  switch (object) {
    case Item_DockerArguments_Volume_VolumeMode.READ_ONLY:
      return 0;
    case Item_DockerArguments_Volume_VolumeMode.READ_WRITE:
      return 1;
    case Item_DockerArguments_Volume_VolumeMode.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Item_DockerArguments_Label {
  key: string;
  value: string;
}

function createBaseItem(): Item {
  return {
    id: "",
    jobId: "",
    versionId: "",
    runnerImage: "",
    runnerAsynchronous: false,
    runnerMinCount: 0,
    runnerMaxCount: 0,
    runnerTimeout: 0,
    runnerMaxIdleAge: 0,
    runnerMaxAge: 0,
    runnerMaxAgeHard: 0,
    dockerArguments: undefined,
    runnerMode: Item_RunnerMode.STANDARD,
  };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.versionId !== "") {
      writer.uint32(26).string(message.versionId);
    }
    if (message.runnerImage !== "") {
      writer.uint32(34).string(message.runnerImage);
    }
    if (message.runnerAsynchronous !== false) {
      writer.uint32(40).bool(message.runnerAsynchronous);
    }
    if (message.runnerMinCount !== 0) {
      writer.uint32(48).uint32(message.runnerMinCount);
    }
    if (message.runnerMaxCount !== 0) {
      writer.uint32(56).uint32(message.runnerMaxCount);
    }
    if (message.runnerTimeout !== 0) {
      writer.uint32(64).uint32(message.runnerTimeout);
    }
    if (message.runnerMaxIdleAge !== 0) {
      writer.uint32(72).uint32(message.runnerMaxIdleAge);
    }
    if (message.runnerMaxAge !== 0) {
      writer.uint32(80).uint32(message.runnerMaxAge);
    }
    if (message.runnerMaxAgeHard !== 0) {
      writer.uint32(88).uint32(message.runnerMaxAgeHard);
    }
    if (message.dockerArguments !== undefined) {
      Item_DockerArguments.encode(message.dockerArguments, writer.uint32(98).fork()).join();
    }
    if (message.runnerMode !== Item_RunnerMode.STANDARD) {
      writer.uint32(104).int32(item_RunnerModeToNumber(message.runnerMode));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.runnerImage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.runnerAsynchronous = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.runnerMinCount = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.runnerMaxCount = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.runnerTimeout = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.runnerMaxIdleAge = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.runnerMaxAge = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.runnerMaxAgeHard = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.dockerArguments = Item_DockerArguments.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.runnerMode = item_RunnerModeFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : "",
      runnerImage: isSet(object.runnerImage) ? globalThis.String(object.runnerImage) : "",
      runnerAsynchronous: isSet(object.runnerAsynchronous) ? globalThis.Boolean(object.runnerAsynchronous) : false,
      runnerMinCount: isSet(object.runnerMinCount) ? globalThis.Number(object.runnerMinCount) : 0,
      runnerMaxCount: isSet(object.runnerMaxCount) ? globalThis.Number(object.runnerMaxCount) : 0,
      runnerTimeout: isSet(object.runnerTimeout) ? globalThis.Number(object.runnerTimeout) : 0,
      runnerMaxIdleAge: isSet(object.runnerMaxIdleAge) ? globalThis.Number(object.runnerMaxIdleAge) : 0,
      runnerMaxAge: isSet(object.runnerMaxAge) ? globalThis.Number(object.runnerMaxAge) : 0,
      runnerMaxAgeHard: isSet(object.runnerMaxAgeHard) ? globalThis.Number(object.runnerMaxAgeHard) : 0,
      dockerArguments: isSet(object.dockerArguments)
        ? Item_DockerArguments.fromJSON(object.dockerArguments)
        : undefined,
      runnerMode: isSet(object.runnerMode) ? item_RunnerModeFromJSON(object.runnerMode) : Item_RunnerMode.STANDARD,
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== "") {
      obj.versionId = message.versionId;
    }
    if (message.runnerImage !== "") {
      obj.runnerImage = message.runnerImage;
    }
    if (message.runnerAsynchronous !== false) {
      obj.runnerAsynchronous = message.runnerAsynchronous;
    }
    if (message.runnerMinCount !== 0) {
      obj.runnerMinCount = Math.round(message.runnerMinCount);
    }
    if (message.runnerMaxCount !== 0) {
      obj.runnerMaxCount = Math.round(message.runnerMaxCount);
    }
    if (message.runnerTimeout !== 0) {
      obj.runnerTimeout = Math.round(message.runnerTimeout);
    }
    if (message.runnerMaxIdleAge !== 0) {
      obj.runnerMaxIdleAge = Math.round(message.runnerMaxIdleAge);
    }
    if (message.runnerMaxAge !== 0) {
      obj.runnerMaxAge = Math.round(message.runnerMaxAge);
    }
    if (message.runnerMaxAgeHard !== 0) {
      obj.runnerMaxAgeHard = Math.round(message.runnerMaxAgeHard);
    }
    if (message.dockerArguments !== undefined) {
      obj.dockerArguments = Item_DockerArguments.toJSON(message.dockerArguments);
    }
    if (message.runnerMode !== Item_RunnerMode.STANDARD) {
      obj.runnerMode = item_RunnerModeToJSON(message.runnerMode);
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? "";
    message.runnerImage = object.runnerImage ?? "";
    message.runnerAsynchronous = object.runnerAsynchronous ?? false;
    message.runnerMinCount = object.runnerMinCount ?? 0;
    message.runnerMaxCount = object.runnerMaxCount ?? 0;
    message.runnerTimeout = object.runnerTimeout ?? 0;
    message.runnerMaxIdleAge = object.runnerMaxIdleAge ?? 0;
    message.runnerMaxAge = object.runnerMaxAge ?? 0;
    message.runnerMaxAgeHard = object.runnerMaxAgeHard ?? 0;
    message.dockerArguments = (object.dockerArguments !== undefined && object.dockerArguments !== null)
      ? Item_DockerArguments.fromPartial(object.dockerArguments)
      : undefined;
    message.runnerMode = object.runnerMode ?? Item_RunnerMode.STANDARD;
    return message;
  },
};

function createBaseItem_DockerArguments(): Item_DockerArguments {
  return { networks: [], volumes: [], labels: [], memoryLimit: undefined, directPassthroughArguments: [] };
}

export const Item_DockerArguments: MessageFns<Item_DockerArguments> = {
  encode(message: Item_DockerArguments, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.networks) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.volumes) {
      Item_DockerArguments_Volume.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.labels) {
      Item_DockerArguments_Label.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.memoryLimit !== undefined) {
      writer.uint32(34).string(message.memoryLimit);
    }
    for (const v of message.directPassthroughArguments) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_DockerArguments {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_DockerArguments();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.networks.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.volumes.push(Item_DockerArguments_Volume.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.labels.push(Item_DockerArguments_Label.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.memoryLimit = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.directPassthroughArguments.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_DockerArguments {
    return {
      networks: globalThis.Array.isArray(object?.networks) ? object.networks.map((e: any) => globalThis.String(e)) : [],
      volumes: globalThis.Array.isArray(object?.volumes)
        ? object.volumes.map((e: any) => Item_DockerArguments_Volume.fromJSON(e))
        : [],
      labels: globalThis.Array.isArray(object?.labels)
        ? object.labels.map((e: any) => Item_DockerArguments_Label.fromJSON(e))
        : [],
      memoryLimit: isSet(object.memoryLimit) ? globalThis.String(object.memoryLimit) : undefined,
      directPassthroughArguments: globalThis.Array.isArray(object?.directPassthroughArguments)
        ? object.directPassthroughArguments.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Item_DockerArguments): unknown {
    const obj: any = {};
    if (message.networks?.length) {
      obj.networks = message.networks;
    }
    if (message.volumes?.length) {
      obj.volumes = message.volumes.map((e) => Item_DockerArguments_Volume.toJSON(e));
    }
    if (message.labels?.length) {
      obj.labels = message.labels.map((e) => Item_DockerArguments_Label.toJSON(e));
    }
    if (message.memoryLimit !== undefined) {
      obj.memoryLimit = message.memoryLimit;
    }
    if (message.directPassthroughArguments?.length) {
      obj.directPassthroughArguments = message.directPassthroughArguments;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_DockerArguments>): Item_DockerArguments {
    return Item_DockerArguments.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_DockerArguments>): Item_DockerArguments {
    const message = createBaseItem_DockerArguments();
    message.networks = object.networks?.map((e) => e) || [];
    message.volumes = object.volumes?.map((e) => Item_DockerArguments_Volume.fromPartial(e)) || [];
    message.labels = object.labels?.map((e) => Item_DockerArguments_Label.fromPartial(e)) || [];
    message.memoryLimit = object.memoryLimit ?? undefined;
    message.directPassthroughArguments = object.directPassthroughArguments?.map((e) => e) || [];
    return message;
  },
};

function createBaseItem_DockerArguments_Volume(): Item_DockerArguments_Volume {
  return { source: "", target: "", mode: Item_DockerArguments_Volume_VolumeMode.READ_ONLY };
}

export const Item_DockerArguments_Volume: MessageFns<Item_DockerArguments_Volume> = {
  encode(message: Item_DockerArguments_Volume, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== "") {
      writer.uint32(10).string(message.source);
    }
    if (message.target !== "") {
      writer.uint32(18).string(message.target);
    }
    if (message.mode !== Item_DockerArguments_Volume_VolumeMode.READ_ONLY) {
      writer.uint32(24).int32(item_DockerArguments_Volume_VolumeModeToNumber(message.mode));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_DockerArguments_Volume {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_DockerArguments_Volume();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.target = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mode = item_DockerArguments_Volume_VolumeModeFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_DockerArguments_Volume {
    return {
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      target: isSet(object.target) ? globalThis.String(object.target) : "",
      mode: isSet(object.mode)
        ? item_DockerArguments_Volume_VolumeModeFromJSON(object.mode)
        : Item_DockerArguments_Volume_VolumeMode.READ_ONLY,
    };
  },

  toJSON(message: Item_DockerArguments_Volume): unknown {
    const obj: any = {};
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.target !== "") {
      obj.target = message.target;
    }
    if (message.mode !== Item_DockerArguments_Volume_VolumeMode.READ_ONLY) {
      obj.mode = item_DockerArguments_Volume_VolumeModeToJSON(message.mode);
    }
    return obj;
  },

  create(base?: DeepPartial<Item_DockerArguments_Volume>): Item_DockerArguments_Volume {
    return Item_DockerArguments_Volume.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_DockerArguments_Volume>): Item_DockerArguments_Volume {
    const message = createBaseItem_DockerArguments_Volume();
    message.source = object.source ?? "";
    message.target = object.target ?? "";
    message.mode = object.mode ?? Item_DockerArguments_Volume_VolumeMode.READ_ONLY;
    return message;
  },
};

function createBaseItem_DockerArguments_Label(): Item_DockerArguments_Label {
  return { key: "", value: "" };
}

export const Item_DockerArguments_Label: MessageFns<Item_DockerArguments_Label> = {
  encode(message: Item_DockerArguments_Label, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_DockerArguments_Label {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_DockerArguments_Label();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_DockerArguments_Label {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Item_DockerArguments_Label): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_DockerArguments_Label>): Item_DockerArguments_Label {
    return Item_DockerArguments_Label.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_DockerArguments_Label>): Item_DockerArguments_Label {
    const message = createBaseItem_DockerArguments_Label();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
