// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Common";

export interface Permission {
  effect: Permission_Effect;
  resource: string;
  actions: Permission_Action[];
}

export const Permission_Effect = { ALLOW: "ALLOW", DENY: "DENY", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type Permission_Effect = typeof Permission_Effect[keyof typeof Permission_Effect];

export namespace Permission_Effect {
  export type ALLOW = typeof Permission_Effect.ALLOW;
  export type DENY = typeof Permission_Effect.DENY;
  export type UNRECOGNIZED = typeof Permission_Effect.UNRECOGNIZED;
}

export function permission_EffectFromJSON(object: any): Permission_Effect {
  switch (object) {
    case 0:
    case "ALLOW":
      return Permission_Effect.ALLOW;
    case 1:
    case "DENY":
      return Permission_Effect.DENY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Permission_Effect.UNRECOGNIZED;
  }
}

export function permission_EffectToJSON(object: Permission_Effect): string {
  switch (object) {
    case Permission_Effect.ALLOW:
      return "ALLOW";
    case Permission_Effect.DENY:
      return "DENY";
    case Permission_Effect.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function permission_EffectToNumber(object: Permission_Effect): number {
  switch (object) {
    case Permission_Effect.ALLOW:
      return 0;
    case Permission_Effect.DENY:
      return 1;
    case Permission_Effect.UNRECOGNIZED:
    default:
      return -1;
  }
}

export const Permission_Action = {
  READ: "READ",
  WRITE: "WRITE",
  DELETE: "DELETE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type Permission_Action = typeof Permission_Action[keyof typeof Permission_Action];

export namespace Permission_Action {
  export type READ = typeof Permission_Action.READ;
  export type WRITE = typeof Permission_Action.WRITE;
  export type DELETE = typeof Permission_Action.DELETE;
  export type UNRECOGNIZED = typeof Permission_Action.UNRECOGNIZED;
}

export function permission_ActionFromJSON(object: any): Permission_Action {
  switch (object) {
    case 0:
    case "READ":
      return Permission_Action.READ;
    case 1:
    case "WRITE":
      return Permission_Action.WRITE;
    case 2:
    case "DELETE":
      return Permission_Action.DELETE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Permission_Action.UNRECOGNIZED;
  }
}

export function permission_ActionToJSON(object: Permission_Action): string {
  switch (object) {
    case Permission_Action.READ:
      return "READ";
    case Permission_Action.WRITE:
      return "WRITE";
    case Permission_Action.DELETE:
      return "DELETE";
    case Permission_Action.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function permission_ActionToNumber(object: Permission_Action): number {
  switch (object) {
    case Permission_Action.READ:
      return 0;
    case Permission_Action.WRITE:
      return 1;
    case Permission_Action.DELETE:
      return 2;
    case Permission_Action.UNRECOGNIZED:
    default:
      return -1;
  }
}

function createBasePermission(): Permission {
  return { effect: Permission_Effect.ALLOW, resource: "", actions: [] };
}

export const Permission: MessageFns<Permission> = {
  encode(message: Permission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.effect !== Permission_Effect.ALLOW) {
      writer.uint32(8).int32(permission_EffectToNumber(message.effect));
    }
    if (message.resource !== "") {
      writer.uint32(18).string(message.resource);
    }
    writer.uint32(26).fork();
    for (const v of message.actions) {
      writer.int32(permission_ActionToNumber(v));
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Permission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePermission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.effect = permission_EffectFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resource = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.actions.push(permission_ActionFromJSON(reader.int32()));

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.actions.push(permission_ActionFromJSON(reader.int32()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Permission {
    return {
      effect: isSet(object.effect) ? permission_EffectFromJSON(object.effect) : Permission_Effect.ALLOW,
      resource: isSet(object.resource) ? globalThis.String(object.resource) : "",
      actions: globalThis.Array.isArray(object?.actions)
        ? object.actions.map((e: any) => permission_ActionFromJSON(e))
        : [],
    };
  },

  toJSON(message: Permission): unknown {
    const obj: any = {};
    if (message.effect !== Permission_Effect.ALLOW) {
      obj.effect = permission_EffectToJSON(message.effect);
    }
    if (message.resource !== "") {
      obj.resource = message.resource;
    }
    if (message.actions?.length) {
      obj.actions = message.actions.map((e) => permission_ActionToJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Permission>): Permission {
    return Permission.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Permission>): Permission {
    const message = createBasePermission();
    message.effect = object.effect ?? Permission_Effect.ALLOW;
    message.resource = object.resource ?? "";
    message.actions = object.actions?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
