// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/environment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Environment";

export interface Item {
  id: string;
  jobId: string;
  context: { [key: string]: Item_ContextValue };
  modified: string;
}

export interface Item_ContextValue {
  type: Item_ContextValue_Type;
  value?: string | undefined;
}

export const Item_ContextValue_Type = { TEXT: "TEXT", SECRET: "SECRET", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type Item_ContextValue_Type = typeof Item_ContextValue_Type[keyof typeof Item_ContextValue_Type];

export namespace Item_ContextValue_Type {
  export type TEXT = typeof Item_ContextValue_Type.TEXT;
  export type SECRET = typeof Item_ContextValue_Type.SECRET;
  export type UNRECOGNIZED = typeof Item_ContextValue_Type.UNRECOGNIZED;
}

export function item_ContextValue_TypeFromJSON(object: any): Item_ContextValue_Type {
  switch (object) {
    case 0:
    case "TEXT":
      return Item_ContextValue_Type.TEXT;
    case 1:
    case "SECRET":
      return Item_ContextValue_Type.SECRET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Item_ContextValue_Type.UNRECOGNIZED;
  }
}

export function item_ContextValue_TypeToJSON(object: Item_ContextValue_Type): string {
  switch (object) {
    case Item_ContextValue_Type.TEXT:
      return "TEXT";
    case Item_ContextValue_Type.SECRET:
      return "SECRET";
    case Item_ContextValue_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function item_ContextValue_TypeToNumber(object: Item_ContextValue_Type): number {
  switch (object) {
    case Item_ContextValue_Type.TEXT:
      return 0;
    case Item_ContextValue_Type.SECRET:
      return 1;
    case Item_ContextValue_Type.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Item_ContextEntry {
  key: string;
  value: Item_ContextValue | undefined;
}

function createBaseItem(): Item {
  return { id: "", jobId: "", context: {}, modified: "" };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    globalThis.Object.entries(message.context).forEach(([key, value]: [string, Item_ContextValue]) => {
      Item_ContextEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.modified !== "") {
      writer.uint32(34).string(message.modified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = Item_ContextEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.context[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.modified = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      context: isObject(object.context)
        ? (globalThis.Object.entries(object.context) as [string, any][]).reduce(
          (acc: { [key: string]: Item_ContextValue }, [key, value]: [string, any]) => {
            acc[key] = Item_ContextValue.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      modified: isSet(object.modified) ? globalThis.String(object.modified) : "",
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.context) {
      const entries = globalThis.Object.entries(message.context) as [string, Item_ContextValue][];
      if (entries.length > 0) {
        obj.context = {};
        entries.forEach(([k, v]) => {
          obj.context[k] = Item_ContextValue.toJSON(v);
        });
      }
    }
    if (message.modified !== "") {
      obj.modified = message.modified;
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.context = (globalThis.Object.entries(object.context ?? {}) as [string, Item_ContextValue][]).reduce(
      (acc: { [key: string]: Item_ContextValue }, [key, value]: [string, Item_ContextValue]) => {
        if (value !== undefined) {
          acc[key] = Item_ContextValue.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.modified = object.modified ?? "";
    return message;
  },
};

function createBaseItem_ContextValue(): Item_ContextValue {
  return { type: Item_ContextValue_Type.TEXT, value: undefined };
}

export const Item_ContextValue: MessageFns<Item_ContextValue> = {
  encode(message: Item_ContextValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== Item_ContextValue_Type.TEXT) {
      writer.uint32(8).int32(item_ContextValue_TypeToNumber(message.type));
    }
    if (message.value !== undefined) {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_ContextValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_ContextValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = item_ContextValue_TypeFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_ContextValue {
    return {
      type: isSet(object.type) ? item_ContextValue_TypeFromJSON(object.type) : Item_ContextValue_Type.TEXT,
      value: isSet(object.value) ? globalThis.String(object.value) : undefined,
    };
  },

  toJSON(message: Item_ContextValue): unknown {
    const obj: any = {};
    if (message.type !== Item_ContextValue_Type.TEXT) {
      obj.type = item_ContextValue_TypeToJSON(message.type);
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_ContextValue>): Item_ContextValue {
    return Item_ContextValue.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_ContextValue>): Item_ContextValue {
    const message = createBaseItem_ContextValue();
    message.type = object.type ?? Item_ContextValue_Type.TEXT;
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseItem_ContextEntry(): Item_ContextEntry {
  return { key: "", value: undefined };
}

export const Item_ContextEntry: MessageFns<Item_ContextEntry> = {
  encode(message: Item_ContextEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Item_ContextValue.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_ContextEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_ContextEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Item_ContextValue.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_ContextEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Item_ContextValue.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: Item_ContextEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Item_ContextValue.toJSON(message.value);
    }
    return obj;
  },

  create(base?: DeepPartial<Item_ContextEntry>): Item_ContextEntry {
    return Item_ContextEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_ContextEntry>): Item_ContextEntry {
    const message = createBaseItem_ContextEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? Item_ContextValue.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
