// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/job.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Job";

export interface Item {
  id: string;
  jobName: string;
  status: Item_Status;
  description?: string | undefined;
  versionId?: string | undefined;
  links: Item_Link[];
}

export const Item_Status = { ENABLED: "ENABLED", DISABLED: "DISABLED", UNRECOGNIZED: "UNRECOGNIZED" } as const;

export type Item_Status = typeof Item_Status[keyof typeof Item_Status];

export namespace Item_Status {
  export type ENABLED = typeof Item_Status.ENABLED;
  export type DISABLED = typeof Item_Status.DISABLED;
  export type UNRECOGNIZED = typeof Item_Status.UNRECOGNIZED;
}

export function item_StatusFromJSON(object: any): Item_Status {
  switch (object) {
    case 0:
    case "ENABLED":
      return Item_Status.ENABLED;
    case 1:
    case "DISABLED":
      return Item_Status.DISABLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Item_Status.UNRECOGNIZED;
  }
}

export function item_StatusToJSON(object: Item_Status): string {
  switch (object) {
    case Item_Status.ENABLED:
      return "ENABLED";
    case Item_Status.DISABLED:
      return "DISABLED";
    case Item_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function item_StatusToNumber(object: Item_Status): number {
  switch (object) {
    case Item_Status.ENABLED:
      return 0;
    case Item_Status.DISABLED:
      return 1;
    case Item_Status.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Item_Link {
  name: string;
  url: string;
}

function createBaseItem(): Item {
  return { id: "", jobName: "", status: Item_Status.ENABLED, description: undefined, versionId: undefined, links: [] };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobName !== "") {
      writer.uint32(18).string(message.jobName);
    }
    if (message.status !== Item_Status.ENABLED) {
      writer.uint32(24).int32(item_StatusToNumber(message.status));
    }
    if (message.description !== undefined) {
      writer.uint32(34).string(message.description);
    }
    if (message.versionId !== undefined) {
      writer.uint32(42).string(message.versionId);
    }
    for (const v of message.links) {
      Item_Link.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = item_StatusFromJSON(reader.int32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.links.push(Item_Link.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobName: isSet(object.jobName) ? globalThis.String(object.jobName) : "",
      status: isSet(object.status) ? item_StatusFromJSON(object.status) : Item_Status.ENABLED,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : undefined,
      links: globalThis.Array.isArray(object?.links) ? object.links.map((e: any) => Item_Link.fromJSON(e)) : [],
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobName !== "") {
      obj.jobName = message.jobName;
    }
    if (message.status !== Item_Status.ENABLED) {
      obj.status = item_StatusToJSON(message.status);
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.versionId !== undefined) {
      obj.versionId = message.versionId;
    }
    if (message.links?.length) {
      obj.links = message.links.map((e) => Item_Link.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.id = object.id ?? "";
    message.jobName = object.jobName ?? "";
    message.status = object.status ?? Item_Status.ENABLED;
    message.description = object.description ?? undefined;
    message.versionId = object.versionId ?? undefined;
    message.links = object.links?.map((e) => Item_Link.fromPartial(e)) || [];
    return message;
  },
};

function createBaseItem_Link(): Item_Link {
  return { name: "", url: "" };
}

export const Item_Link: MessageFns<Item_Link> = {
  encode(message: Item_Link, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_Link {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_Link();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_Link {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
    };
  },

  toJSON(message: Item_Link): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_Link>): Item_Link {
    return Item_Link.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_Link>): Item_Link {
    const message = createBaseItem_Link();
    message.name = object.name ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
