// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/runner.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Runner";

export interface Item {
  id: string;
  jobId: string;
  actionId: string;
  versionId: string;
  properties: Item_Properties | undefined;
  createdAt: string;
  readyAt?: string | undefined;
  closingAt?: string | undefined;
  closedAt?: string | undefined;
}

export const Item_Status = {
  STARTING: "STARTING",
  READY: "READY",
  CLOSING: "CLOSING",
  CLOSED: "CLOSED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type Item_Status = typeof Item_Status[keyof typeof Item_Status];

export namespace Item_Status {
  export type STARTING = typeof Item_Status.STARTING;
  export type READY = typeof Item_Status.READY;
  export type CLOSING = typeof Item_Status.CLOSING;
  export type CLOSED = typeof Item_Status.CLOSED;
  export type UNRECOGNIZED = typeof Item_Status.UNRECOGNIZED;
}

export function item_StatusFromJSON(object: any): Item_Status {
  switch (object) {
    case 0:
    case "STARTING":
      return Item_Status.STARTING;
    case 1:
    case "READY":
      return Item_Status.READY;
    case 2:
    case "CLOSING":
      return Item_Status.CLOSING;
    case 3:
    case "CLOSED":
      return Item_Status.CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Item_Status.UNRECOGNIZED;
  }
}

export function item_StatusToJSON(object: Item_Status): string {
  switch (object) {
    case Item_Status.STARTING:
      return "STARTING";
    case Item_Status.READY:
      return "READY";
    case Item_Status.CLOSING:
      return "CLOSING";
    case Item_Status.CLOSED:
      return "CLOSED";
    case Item_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function item_StatusToNumber(object: Item_Status): number {
  switch (object) {
    case Item_Status.STARTING:
      return 0;
    case Item_Status.READY:
      return 1;
    case Item_Status.CLOSING:
      return 2;
    case Item_Status.CLOSED:
      return 3;
    case Item_Status.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Item_Properties {
  runnerPid: string;
  runnerContainerName: string;
  runnerContainerNetworks: string[];
  runnerApiPort: number;
  runnerDebug: boolean;
}

function createBaseItem(): Item {
  return {
    id: "",
    jobId: "",
    actionId: "",
    versionId: "",
    properties: undefined,
    createdAt: "",
    readyAt: undefined,
    closingAt: undefined,
    closedAt: undefined,
  };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.actionId !== "") {
      writer.uint32(26).string(message.actionId);
    }
    if (message.versionId !== "") {
      writer.uint32(34).string(message.versionId);
    }
    if (message.properties !== undefined) {
      Item_Properties.encode(message.properties, writer.uint32(42).fork()).join();
    }
    if (message.createdAt !== "") {
      writer.uint32(90).string(message.createdAt);
    }
    if (message.readyAt !== undefined) {
      writer.uint32(98).string(message.readyAt);
    }
    if (message.closingAt !== undefined) {
      writer.uint32(106).string(message.closingAt);
    }
    if (message.closedAt !== undefined) {
      writer.uint32(114).string(message.closedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.properties = Item_Properties.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.readyAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.closingAt = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.closedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : "",
      properties: isSet(object.properties) ? Item_Properties.fromJSON(object.properties) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      readyAt: isSet(object.readyAt) ? globalThis.String(object.readyAt) : undefined,
      closingAt: isSet(object.closingAt) ? globalThis.String(object.closingAt) : undefined,
      closedAt: isSet(object.closedAt) ? globalThis.String(object.closedAt) : undefined,
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.versionId !== "") {
      obj.versionId = message.versionId;
    }
    if (message.properties !== undefined) {
      obj.properties = Item_Properties.toJSON(message.properties);
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.readyAt !== undefined) {
      obj.readyAt = message.readyAt;
    }
    if (message.closingAt !== undefined) {
      obj.closingAt = message.closingAt;
    }
    if (message.closedAt !== undefined) {
      obj.closedAt = message.closedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.actionId = object.actionId ?? "";
    message.versionId = object.versionId ?? "";
    message.properties = (object.properties !== undefined && object.properties !== null)
      ? Item_Properties.fromPartial(object.properties)
      : undefined;
    message.createdAt = object.createdAt ?? "";
    message.readyAt = object.readyAt ?? undefined;
    message.closingAt = object.closingAt ?? undefined;
    message.closedAt = object.closedAt ?? undefined;
    return message;
  },
};

function createBaseItem_Properties(): Item_Properties {
  return { runnerPid: "", runnerContainerName: "", runnerContainerNetworks: [], runnerApiPort: 0, runnerDebug: false };
}

export const Item_Properties: MessageFns<Item_Properties> = {
  encode(message: Item_Properties, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runnerPid !== "") {
      writer.uint32(10).string(message.runnerPid);
    }
    if (message.runnerContainerName !== "") {
      writer.uint32(26).string(message.runnerContainerName);
    }
    for (const v of message.runnerContainerNetworks) {
      writer.uint32(34).string(v!);
    }
    if (message.runnerApiPort !== 0) {
      writer.uint32(40).uint32(message.runnerApiPort);
    }
    if (message.runnerDebug !== false) {
      writer.uint32(48).bool(message.runnerDebug);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_Properties {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_Properties();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runnerPid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.runnerContainerName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.runnerContainerNetworks.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.runnerApiPort = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.runnerDebug = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_Properties {
    return {
      runnerPid: isSet(object.runnerPid) ? globalThis.String(object.runnerPid) : "",
      runnerContainerName: isSet(object.runnerContainerName) ? globalThis.String(object.runnerContainerName) : "",
      runnerContainerNetworks: globalThis.Array.isArray(object?.runnerContainerNetworks)
        ? object.runnerContainerNetworks.map((e: any) => globalThis.String(e))
        : [],
      runnerApiPort: isSet(object.runnerApiPort) ? globalThis.Number(object.runnerApiPort) : 0,
      runnerDebug: isSet(object.runnerDebug) ? globalThis.Boolean(object.runnerDebug) : false,
    };
  },

  toJSON(message: Item_Properties): unknown {
    const obj: any = {};
    if (message.runnerPid !== "") {
      obj.runnerPid = message.runnerPid;
    }
    if (message.runnerContainerName !== "") {
      obj.runnerContainerName = message.runnerContainerName;
    }
    if (message.runnerContainerNetworks?.length) {
      obj.runnerContainerNetworks = message.runnerContainerNetworks;
    }
    if (message.runnerApiPort !== 0) {
      obj.runnerApiPort = Math.round(message.runnerApiPort);
    }
    if (message.runnerDebug !== false) {
      obj.runnerDebug = message.runnerDebug;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_Properties>): Item_Properties {
    return Item_Properties.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_Properties>): Item_Properties {
    const message = createBaseItem_Properties();
    message.runnerPid = object.runnerPid ?? "";
    message.runnerContainerName = object.runnerContainerName ?? "";
    message.runnerContainerNetworks = object.runnerContainerNetworks?.map((e) => e) || [];
    message.runnerApiPort = object.runnerApiPort ?? 0;
    message.runnerDebug = object.runnerDebug ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
