// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/runner.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Runner";

export interface Item {
  id: string;
  jobId: string;
  actionId: string;
  status: Item_Status;
  createdAt: string;
  readyAt?: string | undefined;
  closingAt?: string | undefined;
  closedAt?: string | undefined;
}

export const Item_Status = {
  STARTING: "STARTING",
  READY: "READY",
  CLOSING: "CLOSING",
  CLOSED: "CLOSED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type Item_Status = typeof Item_Status[keyof typeof Item_Status];

export namespace Item_Status {
  export type STARTING = typeof Item_Status.STARTING;
  export type READY = typeof Item_Status.READY;
  export type CLOSING = typeof Item_Status.CLOSING;
  export type CLOSED = typeof Item_Status.CLOSED;
  export type UNRECOGNIZED = typeof Item_Status.UNRECOGNIZED;
}

export function item_StatusFromJSON(object: any): Item_Status {
  switch (object) {
    case 0:
    case "STARTING":
      return Item_Status.STARTING;
    case 1:
    case "READY":
      return Item_Status.READY;
    case 2:
    case "CLOSING":
      return Item_Status.CLOSING;
    case 3:
    case "CLOSED":
      return Item_Status.CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Item_Status.UNRECOGNIZED;
  }
}

export function item_StatusToJSON(object: Item_Status): string {
  switch (object) {
    case Item_Status.STARTING:
      return "STARTING";
    case Item_Status.READY:
      return "READY";
    case Item_Status.CLOSING:
      return "CLOSING";
    case Item_Status.CLOSED:
      return "CLOSED";
    case Item_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function item_StatusToNumber(object: Item_Status): number {
  switch (object) {
    case Item_Status.STARTING:
      return 0;
    case Item_Status.READY:
      return 1;
    case Item_Status.CLOSING:
      return 2;
    case Item_Status.CLOSED:
      return 3;
    case Item_Status.UNRECOGNIZED:
    default:
      return -1;
  }
}

function createBaseItem(): Item {
  return {
    id: "",
    jobId: "",
    actionId: "",
    status: Item_Status.STARTING,
    createdAt: "",
    readyAt: undefined,
    closingAt: undefined,
    closedAt: undefined,
  };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.actionId !== "") {
      writer.uint32(26).string(message.actionId);
    }
    if (message.status !== Item_Status.STARTING) {
      writer.uint32(32).int32(item_StatusToNumber(message.status));
    }
    if (message.createdAt !== "") {
      writer.uint32(90).string(message.createdAt);
    }
    if (message.readyAt !== undefined) {
      writer.uint32(98).string(message.readyAt);
    }
    if (message.closingAt !== undefined) {
      writer.uint32(106).string(message.closingAt);
    }
    if (message.closedAt !== undefined) {
      writer.uint32(114).string(message.closedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = item_StatusFromJSON(reader.int32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.readyAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.closingAt = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.closedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
      status: isSet(object.status) ? item_StatusFromJSON(object.status) : Item_Status.STARTING,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      readyAt: isSet(object.readyAt) ? globalThis.String(object.readyAt) : undefined,
      closingAt: isSet(object.closingAt) ? globalThis.String(object.closingAt) : undefined,
      closedAt: isSet(object.closedAt) ? globalThis.String(object.closedAt) : undefined,
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.status !== Item_Status.STARTING) {
      obj.status = item_StatusToJSON(message.status);
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.readyAt !== undefined) {
      obj.readyAt = message.readyAt;
    }
    if (message.closingAt !== undefined) {
      obj.closingAt = message.closingAt;
    }
    if (message.closedAt !== undefined) {
      obj.closedAt = message.closedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.actionId = object.actionId ?? "";
    message.status = object.status ?? Item_Status.STARTING;
    message.createdAt = object.createdAt ?? "";
    message.readyAt = object.readyAt ?? undefined;
    message.closingAt = object.closingAt ?? undefined;
    message.closedAt = object.closedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
