// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.21.12
// source: basics/trigger.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "Trigger";

export interface Item {
  id: string;
  jobId: string;
  versionId: string;
  schedule?: Item_TriggerSchedule | undefined;
  http?: Item_TriggerHttp | undefined;
  mqtt?: Item_TriggerMqtt | undefined;
}

export interface Item_TriggerSchedule {
  name?: string | undefined;
  cron: string;
  timezone?: string | undefined;
}

export interface Item_TriggerHttp {
  name?: string | undefined;
  hostname?: string | undefined;
  method?: string | undefined;
  path?: string | undefined;
}

export interface Item_TriggerMqtt {
  name?: string | undefined;
  topics: string[];
  connection: Item_TriggerMqtt_Connection | undefined;
}

export interface Item_TriggerMqtt_Connection {
  protocol?: string | undefined;
  protocolVariable?: string | undefined;
  port?: string | undefined;
  portVariable?: string | undefined;
  host?: string | undefined;
  hostVariable?: string | undefined;
  username?: string | undefined;
  usernameVariable?: string | undefined;
  password?: string | undefined;
  passwordVariable?: string | undefined;
  clientId?: string | undefined;
  clientIdVariable?: string | undefined;
}

function createBaseItem(): Item {
  return { id: "", jobId: "", versionId: "", schedule: undefined, http: undefined, mqtt: undefined };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.versionId !== "") {
      writer.uint32(26).string(message.versionId);
    }
    if (message.schedule !== undefined) {
      Item_TriggerSchedule.encode(message.schedule, writer.uint32(34).fork()).join();
    }
    if (message.http !== undefined) {
      Item_TriggerHttp.encode(message.http, writer.uint32(42).fork()).join();
    }
    if (message.mqtt !== undefined) {
      Item_TriggerMqtt.encode(message.mqtt, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.versionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.schedule = Item_TriggerSchedule.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.http = Item_TriggerHttp.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mqtt = Item_TriggerMqtt.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId) ? globalThis.String(object.jobId) : "",
      versionId: isSet(object.versionId) ? globalThis.String(object.versionId) : "",
      schedule: isSet(object.schedule) ? Item_TriggerSchedule.fromJSON(object.schedule) : undefined,
      http: isSet(object.http) ? Item_TriggerHttp.fromJSON(object.http) : undefined,
      mqtt: isSet(object.mqtt) ? Item_TriggerMqtt.fromJSON(object.mqtt) : undefined,
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.versionId !== "") {
      obj.versionId = message.versionId;
    }
    if (message.schedule !== undefined) {
      obj.schedule = Item_TriggerSchedule.toJSON(message.schedule);
    }
    if (message.http !== undefined) {
      obj.http = Item_TriggerHttp.toJSON(message.http);
    }
    if (message.mqtt !== undefined) {
      obj.mqtt = Item_TriggerMqtt.toJSON(message.mqtt);
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.versionId = object.versionId ?? "";
    message.schedule = (object.schedule !== undefined && object.schedule !== null)
      ? Item_TriggerSchedule.fromPartial(object.schedule)
      : undefined;
    message.http = (object.http !== undefined && object.http !== null)
      ? Item_TriggerHttp.fromPartial(object.http)
      : undefined;
    message.mqtt = (object.mqtt !== undefined && object.mqtt !== null)
      ? Item_TriggerMqtt.fromPartial(object.mqtt)
      : undefined;
    return message;
  },
};

function createBaseItem_TriggerSchedule(): Item_TriggerSchedule {
  return { name: undefined, cron: "", timezone: undefined };
}

export const Item_TriggerSchedule: MessageFns<Item_TriggerSchedule> = {
  encode(message: Item_TriggerSchedule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined) {
      writer.uint32(10).string(message.name);
    }
    if (message.cron !== "") {
      writer.uint32(18).string(message.cron);
    }
    if (message.timezone !== undefined) {
      writer.uint32(26).string(message.timezone);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_TriggerSchedule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_TriggerSchedule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cron = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_TriggerSchedule {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      cron: isSet(object.cron) ? globalThis.String(object.cron) : "",
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : undefined,
    };
  },

  toJSON(message: Item_TriggerSchedule): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.cron !== "") {
      obj.cron = message.cron;
    }
    if (message.timezone !== undefined) {
      obj.timezone = message.timezone;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_TriggerSchedule>): Item_TriggerSchedule {
    return Item_TriggerSchedule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_TriggerSchedule>): Item_TriggerSchedule {
    const message = createBaseItem_TriggerSchedule();
    message.name = object.name ?? undefined;
    message.cron = object.cron ?? "";
    message.timezone = object.timezone ?? undefined;
    return message;
  },
};

function createBaseItem_TriggerHttp(): Item_TriggerHttp {
  return { name: undefined, hostname: undefined, method: undefined, path: undefined };
}

export const Item_TriggerHttp: MessageFns<Item_TriggerHttp> = {
  encode(message: Item_TriggerHttp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined) {
      writer.uint32(10).string(message.name);
    }
    if (message.hostname !== undefined) {
      writer.uint32(18).string(message.hostname);
    }
    if (message.method !== undefined) {
      writer.uint32(26).string(message.method);
    }
    if (message.path !== undefined) {
      writer.uint32(34).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_TriggerHttp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_TriggerHttp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_TriggerHttp {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : undefined,
      method: isSet(object.method) ? globalThis.String(object.method) : undefined,
      path: isSet(object.path) ? globalThis.String(object.path) : undefined,
    };
  },

  toJSON(message: Item_TriggerHttp): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.hostname !== undefined) {
      obj.hostname = message.hostname;
    }
    if (message.method !== undefined) {
      obj.method = message.method;
    }
    if (message.path !== undefined) {
      obj.path = message.path;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_TriggerHttp>): Item_TriggerHttp {
    return Item_TriggerHttp.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_TriggerHttp>): Item_TriggerHttp {
    const message = createBaseItem_TriggerHttp();
    message.name = object.name ?? undefined;
    message.hostname = object.hostname ?? undefined;
    message.method = object.method ?? undefined;
    message.path = object.path ?? undefined;
    return message;
  },
};

function createBaseItem_TriggerMqtt(): Item_TriggerMqtt {
  return { name: undefined, topics: [], connection: undefined };
}

export const Item_TriggerMqtt: MessageFns<Item_TriggerMqtt> = {
  encode(message: Item_TriggerMqtt, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined) {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.topics) {
      writer.uint32(18).string(v!);
    }
    if (message.connection !== undefined) {
      Item_TriggerMqtt_Connection.encode(message.connection, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_TriggerMqtt {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_TriggerMqtt();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.topics.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connection = Item_TriggerMqtt_Connection.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_TriggerMqtt {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      topics: globalThis.Array.isArray(object?.topics) ? object.topics.map((e: any) => globalThis.String(e)) : [],
      connection: isSet(object.connection) ? Item_TriggerMqtt_Connection.fromJSON(object.connection) : undefined,
    };
  },

  toJSON(message: Item_TriggerMqtt): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.topics?.length) {
      obj.topics = message.topics;
    }
    if (message.connection !== undefined) {
      obj.connection = Item_TriggerMqtt_Connection.toJSON(message.connection);
    }
    return obj;
  },

  create(base?: DeepPartial<Item_TriggerMqtt>): Item_TriggerMqtt {
    return Item_TriggerMqtt.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_TriggerMqtt>): Item_TriggerMqtt {
    const message = createBaseItem_TriggerMqtt();
    message.name = object.name ?? undefined;
    message.topics = object.topics?.map((e) => e) || [];
    message.connection = (object.connection !== undefined && object.connection !== null)
      ? Item_TriggerMqtt_Connection.fromPartial(object.connection)
      : undefined;
    return message;
  },
};

function createBaseItem_TriggerMqtt_Connection(): Item_TriggerMqtt_Connection {
  return {
    protocol: undefined,
    protocolVariable: undefined,
    port: undefined,
    portVariable: undefined,
    host: undefined,
    hostVariable: undefined,
    username: undefined,
    usernameVariable: undefined,
    password: undefined,
    passwordVariable: undefined,
    clientId: undefined,
    clientIdVariable: undefined,
  };
}

export const Item_TriggerMqtt_Connection: MessageFns<Item_TriggerMqtt_Connection> = {
  encode(message: Item_TriggerMqtt_Connection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocol !== undefined) {
      writer.uint32(10).string(message.protocol);
    }
    if (message.protocolVariable !== undefined) {
      writer.uint32(18).string(message.protocolVariable);
    }
    if (message.port !== undefined) {
      writer.uint32(26).string(message.port);
    }
    if (message.portVariable !== undefined) {
      writer.uint32(34).string(message.portVariable);
    }
    if (message.host !== undefined) {
      writer.uint32(42).string(message.host);
    }
    if (message.hostVariable !== undefined) {
      writer.uint32(50).string(message.hostVariable);
    }
    if (message.username !== undefined) {
      writer.uint32(58).string(message.username);
    }
    if (message.usernameVariable !== undefined) {
      writer.uint32(66).string(message.usernameVariable);
    }
    if (message.password !== undefined) {
      writer.uint32(74).string(message.password);
    }
    if (message.passwordVariable !== undefined) {
      writer.uint32(82).string(message.passwordVariable);
    }
    if (message.clientId !== undefined) {
      writer.uint32(90).string(message.clientId);
    }
    if (message.clientIdVariable !== undefined) {
      writer.uint32(98).string(message.clientIdVariable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_TriggerMqtt_Connection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem_TriggerMqtt_Connection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.protocol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.protocolVariable = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.port = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.portVariable = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.hostVariable = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.usernameVariable = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.passwordVariable = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.clientIdVariable = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item_TriggerMqtt_Connection {
    return {
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : undefined,
      protocolVariable: isSet(object.protocolVariable) ? globalThis.String(object.protocolVariable) : undefined,
      port: isSet(object.port) ? globalThis.String(object.port) : undefined,
      portVariable: isSet(object.portVariable) ? globalThis.String(object.portVariable) : undefined,
      host: isSet(object.host) ? globalThis.String(object.host) : undefined,
      hostVariable: isSet(object.hostVariable) ? globalThis.String(object.hostVariable) : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : undefined,
      usernameVariable: isSet(object.usernameVariable) ? globalThis.String(object.usernameVariable) : undefined,
      password: isSet(object.password) ? globalThis.String(object.password) : undefined,
      passwordVariable: isSet(object.passwordVariable) ? globalThis.String(object.passwordVariable) : undefined,
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : undefined,
      clientIdVariable: isSet(object.clientIdVariable) ? globalThis.String(object.clientIdVariable) : undefined,
    };
  },

  toJSON(message: Item_TriggerMqtt_Connection): unknown {
    const obj: any = {};
    if (message.protocol !== undefined) {
      obj.protocol = message.protocol;
    }
    if (message.protocolVariable !== undefined) {
      obj.protocolVariable = message.protocolVariable;
    }
    if (message.port !== undefined) {
      obj.port = message.port;
    }
    if (message.portVariable !== undefined) {
      obj.portVariable = message.portVariable;
    }
    if (message.host !== undefined) {
      obj.host = message.host;
    }
    if (message.hostVariable !== undefined) {
      obj.hostVariable = message.hostVariable;
    }
    if (message.username !== undefined) {
      obj.username = message.username;
    }
    if (message.usernameVariable !== undefined) {
      obj.usernameVariable = message.usernameVariable;
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    if (message.passwordVariable !== undefined) {
      obj.passwordVariable = message.passwordVariable;
    }
    if (message.clientId !== undefined) {
      obj.clientId = message.clientId;
    }
    if (message.clientIdVariable !== undefined) {
      obj.clientIdVariable = message.clientIdVariable;
    }
    return obj;
  },

  create(base?: DeepPartial<Item_TriggerMqtt_Connection>): Item_TriggerMqtt_Connection {
    return Item_TriggerMqtt_Connection.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item_TriggerMqtt_Connection>): Item_TriggerMqtt_Connection {
    const message = createBaseItem_TriggerMqtt_Connection();
    message.protocol = object.protocol ?? undefined;
    message.protocolVariable = object.protocolVariable ?? undefined;
    message.port = object.port ?? undefined;
    message.portVariable = object.portVariable ?? undefined;
    message.host = object.host ?? undefined;
    message.hostVariable = object.hostVariable ?? undefined;
    message.username = object.username ?? undefined;
    message.usernameVariable = object.usernameVariable ?? undefined;
    message.password = object.password ?? undefined;
    message.passwordVariable = object.passwordVariable ?? undefined;
    message.clientId = object.clientId ?? undefined;
    message.clientIdVariable = object.clientIdVariable ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
